### ISSUE TITLE
Running benchmarks from different msbuild configuration doesn't work

### ISSUE THREAD

**Issue by lucabol** [dotnet/BenchmarkDotNet#1029]
Hi guys,
Perhaps there is a workaround or I am missing something. I am using msbuild configurations to treat a single project as a library, exe, xunit test, and banchmarkdotnet tests. I am failing in the latter. In essence if I conditionally import the BenchmarkDotNet package in my csproj file as in:

```
  <PropertyGroup Condition="'$(Configuration)'=='Bench'">
    <DefineConstants>$(DefineConstants);RELEASE;TRACE;BENCH</DefineConstants>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup  Condition="'$(Configuration)'=='Bench'">
    <PackageReference Include="BenchmarkDotNet" Version="0.11.3" />
  </ItemGroup>
```

I am not able to run the benchmarks from my Bench configuration `dotnet run -c Bench`, getting an:

```
4\BenchmarkDotNet.Autogenerated.csproj]
deba8ac9-fbaa-46b8-b898-f954bbb7cbc4.notcs(10,23): error CS0234: The type or namespace name 'Characteristics' does not exist in the namespace 'BenchmarkDotNet' (are you missing an assembly reference?) [C:\dev\SingleSourceProject\bin\bench\netcoreapp3.0\deba8ac9-fbaa-46b8-b898-f954bbb7cbc4\BenchmarkDotNet.Autogenerated.csproj]
```
Notice that if I use the `[InProcessAttribute]`, everything works, so it must be a problem with the generated projects.

To repro, unzip the attached and run:

```
dotnet build -c Bench
dotnet run -c Bench
```
[SingleSourceProject.zip](https://github.com/dotnet/BenchmarkDotNet/files/2803895/SingleSourceProject.zip)

**Comment by adamsitnik** [comment]
Hi @lucabol 

Yes, by default BDN builds the auto-generated project in `Release` configuration. You can use `job.WithCustomBuildConfiguration("Bench")` to tell it to use the `Bench` configuration

```cs
class Program
{
    static void Main(string[] args) => BenchmarkSwitcher
        .FromAssembly(typeof(Program).Assembly)
        .Run(args, DefaultConfig.Instance.With(Job.Default.WithCustomBuildConfiguration("Bench")));
}
```

 > I am using msbuild configurations to treat a single project as a library, exe, xunit test, and banchmarkdotnet tests

this is rather an anti-pattern. You should have separate projects for unit tests and benchmarks.

**Comment by adamsitnik** [comment]
Some time ago I have ported few thousands of CoreFX benchmarks to dotnet/performance repository. 

When developers keep the benchmarks with unit tests they tend to treat benchmarks as unit tests:

- add a test case for every edge case, which results in having hundreds of benchmarks and a long time to run the benchmarks. When it takes too much time to run the benchmarks, the developers stop using them and the performance culture dies...
- add asserts to benchmarks to test their correctness, which results in Asserts being included in the measured time.

A good example: https://github.com/dotnet/corefx/blob/ae38b7cc3762d832fdcebe27a0aab7b22ab2f3fa/src/System.ComponentModel.TypeConverter/tests/Performance/Perf.TypeDescriptorTests.cs#L59-L61

```cs
using (iteration.StartMeasurement())
    for (int i = 0; i < innerIterations; i++)
    {
        TypeConverter converter = TypeDescriptor.GetConverter(typeToConvert);
        Assert.NotNull(converter);
        Assert.Equal(expectedConverter, converter.GetType());
        Assert.True(converter.CanConvertTo(typeof(string)));
    }
```

IMHO we should keep the performance and unit tests in separate projects, mostly because they are just different and require different approach.

**Comment by lucabol** [comment]
That's not what I am experimenting with. In this system conditional compilation and separate msbuild configurations keep tests, benchmark, real code etc.. in different binaries, despite being in just one project.

I have one MyLibrary.cs file with the real code, one MyLibrary.Tests.cs, one MyLibrary.Bench.cs, one MyLibrary.Main.cs in the same project. It reduces scaffolding and keep related things together.

Then by doing one of the following I build (and run) whatever I want:
 ```
dotnet build -c Test
dotnet build -c Bench
dotnet run -c Bench
dotnet test -c Test
```

To this point, it all seems to work rather nicely. The most irritating thing is lack of intellisense for conditionally compiled out parts of code. But perhaps I'll come up with a trick to do it.

Not suggesting this idea as 'production' ready, just playing with it at this point. We'll see if it breaks down at some point.

**Comment by adamsitnik** [comment]
It's a trade-off: code complexity (`#if defines`) and .csproj complexity (custom build configurations that you need to explain to others) for a single project and running commands from the same folder.

@lucabol it's your project, I just wanted to say that for me it's an anti-pattern (something that initially seems to be a good idea, but turns out bad later). 

Anyway, thanks for using BenchmarkDotNet and giving it a try! Have a nice day!

**Comment by lucabol** [comment]
Cheers. There are pros and cons both ways. I wouldn't use this for a team of people as it is not mainstream enough, but for my own personal projects it's an interesting option (for me).

BTW: BDN is just great! You guys keep up the good work!
