### ISSUE TITLE
Visual Studio Extension

### ISSUE THREAD

**Issue by szehetner** [dotnet/BenchmarkDotNet#1063]
I have started to build a Visual Studio extension to explore and run benchmarks: https://github.com/szehetner/BenchmarkDotNet-VS-Runner

![Benchmark Runner Window](https://github.com/szehetner/BenchmarkDotNet-VS-Runner/raw/master/src/BenchmarkRunner/Sample.png)

The idea is to have a UnitTest-runner-like UI that just starts BenchmarkDotNet with the right command line parameters. It's not quite finished yet, but the basic workflow is there. 

Feedback welcome!

**Comment by omariom** [comment]
Great idea!

Would be convenient to have a tab with results in datagrid so I can sort (or even group) by any columns.

**Comment by szehetner** [comment]
Good idea, this shouldn't be hard to add. https://github.com/szehetner/BenchmarkDotNet-VS-Runner/issues/1

**Comment by mantzas** [comment]
Visual studio code would be nice too...

**Comment by szehetner** [comment]
Yes, but the extension model for VS Code is completely different to Visual Studio, so this would basically be a re-implementation. Which also makes it a task for somebody with a lot more VS Code experience.

**Comment by mantzas** [comment]
@szehetner should i open another ticket? Maybe someone might jump at the chance to do this...

**Comment by szehetner** [comment]
@mantzas Sure, maybe somebody elso will pick it up.

**Comment by AndreyAkinshin** [comment]
@szehetner your extension looks nice, thanks for sharing. However, I'm going to close this issue since there are no reasons to keep it open.

P.S. I'm working on my own plugin for [Rider](https://www.jetbrains.com/rider/) and [ReSharper](https://www.jetbrains.com/resharper/). Some of the features that I want to implement:

* All the IDE activities should be suspended during benchmark run (not sure that it's possible in VS, but it should be possible in Rider).
* Users should be able to group any subset of benchmarks to a session (similar to ReSharper/Rider [Unit Test Session](https://www.jetbrains.com/help/resharper/Using_Unit_Test_Sessions.html))
* Nice table view for the summary table which supports filtering/regrouping.
