### ISSUE TITLE
The error message for users who want to Debug benchmarks is not clear

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1073]
The error message for users who want to Debug benchmarks is not clear, it suggests using `JitOptimizationsValidator.DontFailOnError` so our users go with `DefaultConfig.Instance.With(JitOptimizationsValidator.DontFailOnError)` and they fail because `DefaultConfig` contains `JitOptimizationsValidator.FailOnError`

I am going to simplify the error message and provide the link to https://benchmarkdotnet.org/articles/guides/troubleshooting.html#debugging-benchmarks

**Comment by adamsitnik** [comment]
we can also suggest `config.With(ConfigOptions.DisableOptimizationsValidator);`

**Comment by Zhentar** [comment]
Neither version works for me...

```cs
public class MyConfig : ManualConfig
{
	public MyConfig() 
	{
		var run = Job.Default.WithMaxRelativeError(0.5)
			.With(new[] { new EnvironmentVariable("COMPlus_TieredCompilation", "0") });
		Add(run);
		Add(JitOptimizationsValidator.DontFailOnError);
	}
}
[Config(typeof(MyConfig))]
public class MyBenchmarks
{
    //...
}
```

The `Add(JitOptimizationsValidator.DontFailOnError)` version isn't great since it just silently does nothing, but the only place it would seem like `.With(ConfigOptions.DisableOptimizationsValidator)` could go won't compile.

Looking at the code, it seems like there isn't any way to do it with a ManualConfig type attribute, so instead I'll have to use
```cs
var config = DefaultConfig.Instance.With(ConfigOptions.DisableOptimizationsValidator);
BenchmarkDotNet.Running.BenchmarkRunner.Run<MyBenchmarks>(config);
```
Which is not a way I've ever set up my benchmarks before and neither version of the error message leads me to.

**Comment by Zhentar** [comment]
I think the `[Attributes]` approach is the most common by far, because that's the approach the introductory samples take. I know I ended up using ManualConfig subclasses because that was what I found first in the docs for more advanced scenarios; don't know if that's common or not. Is there an attribute that can resolve this? Would said attribute still work in combination with ManualConfig or fluent api config? If the answer to both of those is or could be "yes", then I think that would make it a clear winner for inclusion in the error message
