### ISSUE TITLE
GenericTypeArguments have to be compile-time constants

### ISSUE THREAD

**Issue by Zhentar** [dotnet/BenchmarkDotNet#1075]
For https://github.com/Zhentar/CLRStackZeroingAssemblyTests I am dynamically generating value types so that they can be used as as generic type parameters, as a way of achieving de-virtualizable delegates. Unfortunately, this means the generic type parameter arguments I want to use for my benchmark are not compile-time constants, which means I have to manually create all of the benchmark types, and invoke them using `BenchmarkSwitcher.FromTypes((...).ToArray()).RunAllJoined();`, and I can only use the In Process toolchain (which cuts me off from a lot of the diagnosers!).

I would really like to be able to do something like this:
```cs
public class MyBenchmarks
{
  [Params(32u, 64u, 128u)]
  public uint BytesToZero { get; set; }

  public Type[] TypeSource() => new [] { TypeGenerate.GenerateForBytes(BytesToZero) };

  [Benchmark]
  [GenericTypeArgumentSource(nameof(TypeSource))]
  public void TestFunction<T>() where T : ITest => default(T).Test();
}
```

With the closed generic delegate on the test function being created via reflection in the process executing the tests rather than relying on the type being known at compile time.

**Comment by adamsitnik** [comment]
Hi @Zhentar 

BenchmarkDotNet generates a boilerplate code which is implemented inside a class that derives from the benchmarked type. You can see the template [here](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Templates/BenchmarkType.txt#L2) or use `--keepFiles` argument to make BDN keep the auto-generated code.

```cs
public class Runnable_0 : MyBenchmarks<int>
```

We could of course use reflection, and generate the following code:

```cd
public class Runnable_0<T> : MyBenchmarks<T>
```

and create it with `Activator.CreateInstance(typeof(Runnable_0<>).MakeGenericType(typeof(T)))`

the problem is that one of the .NET `AOT` runtimes that we support, CoreRT does not support it.

I am sorry, but we won't be able to implement it because of that.

> I can only use the In Process toolchain (which cuts me off from a lot of the diagnosers!).

I think that we should be able to get most of the diagnosers working with InProcessToolchain, please create an issue for that.
