### ISSUE TITLE
Get count of Benchmark return value

### ISSUE THREAD

**Issue by karanbhamra** [dotnet/BenchmarkDotNet#1166]
So  I have the following code in which I am grabbing a pdf file with selenium and seeing if it succeeded or not. Is there anyway to see how many of the iterations returned true or false since the benchmark function returns the bool? I would need to know how many are success or failure within the benchmark
        

		[Benchmark]
        public bool W3Pdf()
        { 
            IWebDriver driver = new FirefoxDriver();      

            driver.Navigate().GoToUrl("https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf");

            string getURL = driver.Url;

            bool success = getURL.Contains(".pdf");

            driver.Quit();
            
            return success;
            
        }

**Comment by AndreyAkinshin** [comment]
We don't have a general feature which keeps all the returned value because of the following reasons:
1. It may affect performance in nanobenchmark cases.
2. Extra storage with the results may affect GC.
3. By default, we execute all the benchmarks in a separate process, so we have to serialize the result somehow.
This issue was already discussed several times (e.g., see #523).

However, you case is interesting because it refers to the error handling (another relevant issue: #373). I guess we can support case when we interpret bool result as a fail/success flag and show a column with the error rate.
@adamsitnik what do you think?

**Comment by adamsitnik** [comment]
I think that it's out of scope of a micro-benchmarking tool.  There are tools designed for testing web servers and generating user load, and @karanbhamra should simply use a different tool.
