### ISSUE TITLE
Running from a C# script

### ISSUE THREAD

**Issue by aelij** [dotnet/BenchmarkDotNet#1191]
C# scripts (`.csx`) generate a class where all the members and inner types of the script reside. The problem is that this class is generated by Roslyn as `internal`, and so BenchmarkDotNet fails to run due to this line:

https://github.com/dotnet/BenchmarkDotNet/blob/dfa074b024cfa8bbe4fe175d3d65a3d9f85127ff/src/BenchmarkDotNet/Running/BenchmarkConverter.cs#L260

Would it be possible to add a configuration option to skip this check?

C# scripts is a main building block of RoslynPad, and I've received a [request](https://github.com/aelij/RoslynPad/issues/285) to support benchmarks there.

**Comment by adamsitnik** [comment]
Hello @aelij 

BenchmarkDotNet generates, builds and runs some boilerplate code to avoid some common benchmarking pitfalls. An example: we consume the result of the benchmark to avoid dead code elimination.

One of the things we do, is we generate a new type that derives from a type which defines the benchmark:

https://github.com/dotnet/BenchmarkDotNet/blob/dfa074b024cfa8bbe4fe175d3d65a3d9f85127ff/src/BenchmarkDotNet/Templates/BenchmarkType.txt#L2

This is why we need to make sure that the type is public, non-static and non-sealed. 

Even if we would remove this line, we would fail later with a different error related to that.

**Comment by aelij** [comment]
Yeah that obviously would not work in a script execution, but in RP you can use the in-process runner: `Job.Default.With(InProcessToolchain.Instance)`.

**Comment by aelij** [comment]
BTW, regarding inheriting from non-public types, it's be possible to circumvent that using the (undocumented) `IgnoresAccessChecksToAttribute`. See [here](https://github.com/aelij/IgnoresAccessChecksToGenerator) for an example.

**Comment by adamsitnik** [comment]
I took a brief look at the source code again. 

I was thinking about removing the mentioned throw for InProcessToolchain only, but there are too many places where we search only for `public` types/methods. So some features would work, some not.

I also don't want to rely on the undocumented `IgnoresAccessChecksToAttribute` since it might have some perf impact we don't know about.

I think that the simplest solution would be to make Roslyn generate public types. @aelij do you have control over that in RoslynPad?

Having said that, I am going to close this issue.

**Comment by aelij** [comment]
Hi Adam, I don't see the downside in adding a option to disable visibility check in `BenchmarkConverter`. As it's already a public API, someone willing to use it at their own risk should be able to do so.

This way I could offer a reasonable workaround for my users.

**Comment by adamsitnik** [comment]
There are simply many, many places where we check for `public` things only. It's not only about removing this one check from `BenchmarkConverter`.

There are also many ways of running the benchmarks via `BenchmarkSwitcher` and `BenchmarkRunner` (users can provide assembly, type, call generic method etc).

For example, our recommended way is to pass an `Assembly` to `BenchmarkSwitcher`.

https://github.com/dotnet/BenchmarkDotNet/blob/728c40e9b74791ade77775f4d486d7bf6ae7940a/samples/BenchmarkDotNet.Samples/Program.cs#L7

Users very often copy-paste this example when they author their first benchmark. Even if we allow for handling internal types in `BenchmarkRunner.Run(Type type)`, they are going to get an error first if they use the recommended way. So they would need to know that they have to use this one specific overload to get it working.

IMHO the best solution would be to emit public types on your side, and on our side add detection of `RoslynPad` similar to the one we have for LINQ and then use `InProcessToolchain`.

https://github.com/dotnet/BenchmarkDotNet/blob/728c40e9b74791ade77775f4d486d7bf6ae7940a/src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs#L48-L49

**Comment by aelij** [comment]
> the best solution would be to emit public types 

As I said, this is out of my control. Roslyn generates a class for each script and it's always internal.

> There are simply many, many places where we check for public things only

The fact is that copying `BenchmarkConverter` into RP, removing the public checks, and using the `InProcessToolchain` **works**. What would be the downside in enabling this specific flow, even if others won't work? I will provide a working sample for my users.

**Comment by adamsitnik** [comment]
> As I said, this is out of my control. Roslyn generates a class for each script and it's always internal.

I've taken a brief look into `RoslynPad` source code. Do you mean that any time you create `CSharpParseOptions` with `Kind` set to `SourceCodeKind.Script` Roslyn generates an internall class and puts the content of the parsed code into it?

https://github.com/aelij/RoslynPad/blob/85cd0745bfe6b8f36bdae107593231fb37ab6d11/src/RoslynPad.Roslyn/Scripting/ScriptRunner.cs#L52-L54

Could you please create an issue in the Roslyn repo and describe the problem? I am going to ask some Roslyn folks to get their attention. IMHO there should be a way to specify that it has to be public.

I really don't want to add any workaround on our end. We did that in the past and it always turned out bad for us (growing code complexity, features hard to kept working)
