### ISSUE TITLE
Can someone explain why my Error time is higher but total time is lower?

### ISSUE THREAD

**Issue by DataJuggler** [dotnet/BenchmarkDotNet#1224]
I have read half of 99.9% confidence level, and I guess before my tiny brain can comprehend 1/2000th of the Confidence Level, I need to understand what Confidence Level means?

My previous benchmark I posted was actually not a valid test, because my configuration settings were  in another project (Win Forms), and I had to switch to a console app to run the tests.

So my previous claim of 14 times faster, just means my tool failed 14 times faster if no configuration was set.

Once I set my connection strings and ran the test again, my project DataTier.Net still runs faster, but the Error section is much higher, so I have no idea what this means.

|         Method |     Mean |     Error |    StdDev |
|--------------- |---------:|----------:|----------:|
| FindDTNSetting | 102.3 us | 2.0215 us | 2.1630 us |
| FindEFSetting | 187.6 us | 0.8109 us | 0.7585 us |

Does this result state my mean time is faster, but has more fluctuation?

As per the question for a better term for Error I read in another recent post, any other word in the English Language would be better than error. <b>1/2000 CL</b> is 100 times more clear than Error.

All you have to do then is define CL, which is why I am here.

Thanks

**Comment by AndreyAkinshin** [comment]
There is a well-known term in statistics called [Standard Error](https://en.wikipedia.org/wiki/Standard_error). The "Error" that is reported by BenchmarkDotNet is actually the standard error multiplied by a special factor. This factor is calculated based on the confidence level and the same size. BenchmarkDotNet reports such kind of "Error" instead of the standard error because it equals to the half of [confidence interval](https://en.wikipedia.org/wiki/Confidence_interval) (another well-known term in statistics) with confidence level 99.9% (this metric is much more useful during analysis than the raw standard error). The "error" word is used because reported Mean values (`102.3 us` and `187.6 us` in your example) are not the exact Mean values of *all* possible durations of your benchmarks, it's just an approximation based on a small sample that you collected during the benchmark runs. The "true" mean value can be calculated only based on *all* possible benchmark runs, but it's impossible to collect all of them because you can run a benchmark as many times as you want. Thus, you always have an error in the Mean column. When the sample size is small, the error may be huge. When you increase the same size, the error decreases. By default, BenchmarkDotNet tries to choose a sample size that provides an optimal trade-off between the error and the total duration of the whole benchmark experiment. The prase "1/2000th of the Confidence Level" doesn't make sense because confidence level for the reported error is always 99.9% (BenchmarkDotNet calculates the size of the confidence interval with the given confidence level=99.9% and divide it by two). By the way, you can find the same notation ("error" as the half of a confidence interval) in other tools (e.g., in [JMH](https://openjdk.java.net/projects/code-tools/jmh/), see https://stackoverflow.com/questions/24723527/what-does-openjdk-jmh-score-error-exactly-mean).
