### ISSUE TITLE
Running as .Net Core Azure webjobs

### ISSUE THREAD

**Issue by TimirP** [dotnet/BenchmarkDotNet#1276]
I tried to run Benchmark as azure webjobs but it always fails. Probably it's not able to create folders to dump the result. Any one else have tried to run it on Azure?  I'm trying to compare performance of Azure Blob in various scenarios. I simply tried to run your Md5VsSha256 sample on Azure.

**Comment by adamsitnik** [comment]
Hi @TimirP 

BenchmarkDotNet supports only console apps. It's by design to make it possible to generate a new project with boilerplate code , reference the project that defines benchmarks, build it and run every benchmark in a dedicated process.

You should be able to use our InProcessToolchain that does not build anything out-proc and just runs the benchmarks using Threads within the same process:

https://benchmarkdotnet.org/articles/configs/toolchains.html#sample-introinprocess

Thanks,
Adam
