### ISSUE TITLE
Implement Unix Disassembler for .NET Core

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1316]
As far as I understand, we could use

- EventPipe (shipped with .NET Core 3.0) to emit .NET Runtime events on Unix
- TraceEvent to consume [MethodILToNativeMap](https://github.com/microsoft/perfview/blob/f35dccc88a2e6d467d26411bb09705375b823b9d/src/TraceEvent/Parsers/ClrTraceEventParser.cs#L1138) events
- Get the `IL` and native code map:
    - use Mono.Cecil to turn byte representation of IL to text
    - use [iced](https://github.com/0xd4d/iced) to turn byte representation of native code to text

It might turn out that some data is missing and|or I am simply wrong and it's impossible to implement it as of today. So it's a challange ;)

**Comment by WojciechNagorski** [comment]
@adamsitnik Because #1315 is blocked I would like to take this one too. Is this issue free?

**Comment by adamsitnik** [comment]
It's still up for grabs. However, I am not sure whether `Microsoft.Diagnostics.NETCore.Client` is already available as NuGet package, so you need to confirm it first. Thanks!

**Comment by WojciechNagorski** [comment]
You're right but I'm going to start with my local build of `Microsoft.Diagnostics.NETCore.Client` from https://github.com/dotnet/diagnostics/pull/617
 
![image](https://user-images.githubusercontent.com/17333903/69706863-e2217a00-10f8-11ea-9928-0f6ad2269146.png)

In this comment https://github.com/dotnet/diagnostics/issues/645#issuecomment-558345643 I got information:
>productized version is almost finished

**Comment by damageboy** [comment]
I actually think this isn't blocked at all.

I mean, I got [JitDasm](https://github.com/0xd4d/JitDasm) to work on my linux box (I make no claims about macOs).

I don't mind taking a stab at this either... I would approach it this way:

* Update to latest ClrMD
* Follow the guidelines for flushing the data target as set out in [ClrMD issue 303](https://github.com/microsoft/clrmd/issues/303)
* Remove the requirement for `IDebugControl` for the disassembly part:
  * I have no idea, nor do I want to know if this is supported on Linux right now
  * Given the current quality of Microsoft diagnostic tooling on Linux, I think a safer approach for now would be "the less the better", at least when it comes to Linux
  * If I understand correctly, the entire reason "we" have two projects for disassembly is because of `IDebugControl` so moving to managed disassembler will help remove this
* Replace the disassembler with [Iced](https://github.com/0xd4d/iced)

Feel free to correct me about any of this, as I've just glanced at the current code and might be wrong about some things here?

Caveats:
* Will not work for Linux on 2.0/2.1/2.2 until [ClrMD issue 303](https://github.com/microsoft/clrmd/issues/303) is fully resolved.

@WojciechNagorski Did you have something else in mind? do you feel strongly about working on this? Would you like me to give it a go?

**Comment by WojciechNagorski** [comment]
@damageboy I think that I would be able to finish this task but if you want to do it you can take this task. I wanted to start the implementation of this task after https://github.com/dotnet/BenchmarkDotNet/pull/1321.

**Comment by adamsitnik** [comment]
If `Iced` works on Linux then we should definitely use it!

**Comment by damageboy** [comment]
@adamsitnik It does. Have been using it on Linux for a few weeks now as part of JitDasm and JitBuddy.
So is CleMD, finally, although support is more fidgety.

So, in general, you approve of a path where we:
* Update ClrMD to latest nuget.
* Replace `IDebugControl` usage with direct usage of `Iced`
* Profit!

?

**Comment by adamsitnik** [comment]
Fixed by #1332
