### ISSUE TITLE
Reuse data generated during benchmark 

### ISSUE THREAD

**Issue by Audionysos** [dotnet/BenchmarkDotNet#1393]
Hello, I've just started playing with your library and I love it, but I think I'm kind of stuck.

Please forgive me, I've tried to describe my problem as short as I can but it's still a little lengthy. 

I want to compare performance of several collection classes. I'm interested in few operations on them: 

- Addition
- Acquisition
- Deletion
- Problem-specific algorithms 

Additionally I would like to be able to compare performance at different scales - as the simple operation time grows with number of used collection elements/items.

So I'm not sure if or how could I reuse previously generated data (generated during measurements).

So far I have following setup:

1. I've created abstract wrapper class for the collection so I can have single test implementation regardless of collection's class interface. 

```C#
public abstract class CollectionInterface {
	private CollectionTestSettings sets;
	public CollectionInterface(CollectionTestSettings sets){
		this.sets = sets;
	}

	public object add() {
		for (int i = 0; i < sets.count; i++) add((uint)i, i);
		return this;
	}

	public object remove() {
		for (int i = 0; i < sets.count; i++) remove((uint)i);
		return this;
	}
    
    //...

	protected abstract void add(uint k, int v);
	protected abstract int get(uint k);
	protected abstract int remove(uint k);

}
```

2. Following is an example implementation for  `SortedDictionary` class:

```C#
public class SortedDictionaryIF : CollectionInterface {
	private SortedDictionary<uint, int> d = new SortedDictionary<uint, int>();

	public SortedDictionaryIF(CollectionTestSettings sets) : base(sets) {}

	protected override void add(uint k, int v) => d.Add(k, v);
	protected override int get(uint k) => d.TryGetValue(k, out var r) ? r : int.MaxValue;
	protected override int remove(uint k) => d.Remove(k, out var r) ? r : int.MaxValue;
}
```

3. Finally this is what my benchmark class looks like (testing only `add` method)

```C#
[RPlotExporter]
public class Benches {
    [ParamsSource(nameof(counts))]
    public int N { get; set; }

    public IEnumerable<int> counts => new[] {
        10, 100, 1_000,// 10_000
    };
    private CollectionTestSettings sets;

    private Benches() {

    }

    [GlobalSetup]
    public void setup() {
        sets = new CollectionTestSettings() {
            count = N
        };
    }

    [Benchmark]
    public object intmapAdd() {
        var col = new IntmapIF(sets);
        return col.add();
    }

    [Benchmark]
    public object dictAdd() {
        var col = new SortedDictionaryIF(sets);
        return col.add();
    }
}
```
And here comes my concerns:

- Testing `add` method itself is time consuming so when I test `remove` method,  I would like to reuse the data previously generated while testing `add` methods.

  ..

- When I test performance of  `add` method for say 10_000, what I'm really getting as a result is an average performance of the method when filling the collection up to 10K items i.e. call to the method when collection had 5 elements is a part of the result. What I would really like to get instead is an average performance of a method at the time the collection had around 10k items. 

  This means I would need to have collection prefilled to 10k every time before "add" method of actual collection class is called.

So if I understand it correctly, currently the benchmark would look similar to this 

```c#
public void bench() {
    var b = new Benches();
    foreach (var n in b.counts) {
        b.N = n;
        b.setup();
        startMeasure();
        for (int i = 0; i < iterationsCount; i++)
            b.intmapAdd();
        stopMeasure();
    }

    foreach (var n in b.counts) {
        b.N = n;
        b.setup();
        startMeasure();
        for (int i = 0; i < iterationsCount; i++)
            b.intmapRemove();
        stopMeasure();
    }

    //...
}
```
Is it possible to do something like this below instead?

```C#
public void benchB() {
    var b = new Benches();
    foreach (var n in b.counts) {
        b.N = n;
        b.setup();
        for (int i = 0; i < iterationsCount; i++) {
            startMeasure("Add");
            b.intmapAdd();
            stopMeasure();

            startMeasure("Remove");
            b.intmapRemove();
            stopMeasure();
        }
    }
}
```
This is still not ideal but it would help a lot. Ideally I would love to have a single test method inside my `CollectionInterface` class where I would switch particular measurements on/off with some tags:

```C#
public void test() {
    startMeasure("whole");
    for (int i = 0; i < sets.count; i++) {
        starMeasure("add");
        add((uint)i, i);
        stopMeasure("add");

        starMeasure("remove");
        remove((uint)i);
        stopMeasure("remove");

    }
    stopMeasure("whole");
}
```
I've already did something similar but it was for another measurements and it doesn't have other cool features which BDN have, and sadly I so far can't see option like above in BDN :[

**Comment by adamsitnik** [comment]
Hi @Audionysos 

This is not going to be easy, for various reasons.

First of all, BenchmarkDotNet assumes that benchmarks have no side effects. So as you said if you want to test `remove` you must set up a collection first. But BenchmarkDotNet runs every benchmark multiple times per single iteration so every invocation needs a clean input.

For this pattern you can use two solutions:

* benchmarks that test both add and remove, a good example is the set of official benchmarks that test the performance of all .NET  Collections:

https://github.com/dotnet/performance/blob/09345d2ca9d03f28359a36ae53e7bc49cc5df543/src/benchmarks/micro/libraries/System.Collections/CreateAddAndRemove.cs#L26-L39

You get an aggregate result, but the benchmark is quite clean and also makes it possible to compare various collections.

* Use a combination  of `[IterationSetup]` to setup every iteration and `[InvocationCount]` to tell BDN how many times given benchmark should be executed per iteration.

A good example is how we test `Sort` in dotnet/performace repo:

https://github.com/dotnet/performance/blob/09345d2ca9d03f28359a36ae53e7bc49cc5df543/src/benchmarks/micro/libraries/System.Collections/Sort.cs#L19

https://github.com/dotnet/performance/blob/09345d2ca9d03f28359a36ae53e7bc49cc5df543/src/benchmarks/micro/libraries/System.Collections/Sort.cs#L33-L44

The problem here is that you need to find a good value for `InvocationCount` (to make enough computations to run for at least 100 ms to get meaningful results) and implement setup method and make sure you use `[IterationSetup]` and `[InvocationCount]` properly .

When it comes to:

```cs
        starMeasure("add");
        add((uint)i, i);
        stopMeasure("add");
```

It's simply impossible for operations that take nanoseconds to execute because the time it takes to start and stop the stopwatch is bigger than the operation itself. So you end up benchmarking stopwatch.

A good alternative is to create benchmarks that test end-to-end scenario that represents typical app workload. An example: a user adds N elements to a collection, performs X an Y and Z operations and finishes.

Some time ago I've written benchmarking guidelines for the .NET Team, I believe that you might find them useful: https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md

**Comment by Audionysos** [comment]
First of all, thank you for quick and exhaustive response. It's nice to know it's not so easy as oppose to that I'm too stupid to do it :) I've read links you've posted and... I have some new thoughts on this. I don't want to disturb your work and I'm not demanding further response but if you don't mind I will add them here. 

```C#
starMeasure("add");
add((uint)i, i);
stopMeasure("add");
```

I think I don't fully understand it. As for stopping it seams more obvious because we processing additional data before actually stopping but how/why process of starting a stopwatch is included in time measured by the stopwatch?

Another thing, assuming the worst scenario where time of whole code above is included in the result. Isn't the time for stopping and starting the watch quite constant?  If we say above code is benchmark **A** and we run following benchmark **B**:

```c#
starMeasure("add");
stopMeasure("add");
```

Isn't **A** - **B** ~ result for `add()` method?

I guess it's more tricky to find actual time of the `add()` method  because of this asymmetric stopwatch starts/stops but still, even if calculating this overhead is not possible, what I'm really interested in as a user are relative times and not really a raw `us` times. 

If I expect benchmark **A** to always produce more or less the same result **x** and I make another benchmark **C** with a result of **y**:

```c#
starMeasure("add");
add2((uint)i, i);
stopMeasure("add");
```

Then If **y** > **x** I still can say the `add()` method is faster then `add2()`. I make a benchmark as a programmer to use the fastest method. So at the end the only information I need is which method is faster, isn't it? 

Similarly for example the loop - should I really care that I use a loop, If in result I'm getting values like 19ns vs 320ns? I mean, even if real result should be 15ns vs 330ns, general conclusion wouldn't change... Also, you just actually proposed to crate typical app workload scenario so I'm not sure how should I eat that information with the one provided [in the link](https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md#Loops)

```C#
[Benchmark]
[Arguments("12345")]
public int ParseNotOk(string value)
{
    int result = 0;
    for (int i = 0; i < 1000; i++)
    {
        result += int.Parse(value);
    }
    return result;
}
```



And finally about `[IterationSetup]`, this really puzzles me from the begging. Especially when it comes to the magic 100ms time and the "**If you don't, your benchmark will be entirely invalid.**". Do you have some time switch or something based on this value? And because I've just recently replaced my 10yo PC and now have 3 times faster CPU clock, does it mean I can run the same benchmark on it and it will be valid, but it will be invalid on my new PC?? I'm literally scratching my head while thinking about this. 

This actually gave me and idea. What if we could use VM with significantly slower clock speed? We would fire our watches on normal clock but the benchmark would run like say 1_000_000 times slower?

**Comment by adamsitnik** [comment]
> I think I don't fully understand it. 

The best explanation that I was able to find so far is @AndreyAkinshin blog post about Stopwatch: https://aakinshin.net/posts/stopwatch/#pitfalls

> Similarly for example the loop - should I really care that I use a loop, If in result I'm getting values like 19ns vs 320ns? 

Yes, and there are many reasons why.

You can run into some benchmarking pitfalls like this: JIT can optimize your loop and replace it with a single operation (if it knows that the result is not changing over time). When you think that reported time shows the sum of `N` operations it's actually the cost of a single one.

Moreover, if you don't introduce the loop, then BDN scales the number of invocations per given machine. If you design your  benchmark with a loop and it takes 0.5s to run on your fast machine, it might take 2.5s to run on your old machine. Which makes you wait for the results 5x longer. I encourage people to avoid that since it hurts performance culture - ppl stop running benchmarks if it takes too long to run them.

> Do you have some time switch or something based on this value?

We just display the warning.

> does it mean I can run the same benchmark on it and it will be valid, but it will be invalid on my new PC??

The results might be inaccurate. This is why we don't recommend to use this feature.

If you want to learn more about benchmarking pitfalls I can highly recommend [PRO .NET Benchmarking](https://aakinshin.net/prodotnetbenchmarking/) by @AndreyAkinshin

**Comment by Audionysos** [comment]
To be honest I'm not convinced with the post you've just linked. The guy shows result where over 93 % of measured delta is less then one tick and over 99,9% is less than 1us and then he claims that because 1 on a million of measured deltas is 0.8ms, we can't rely on Stopwatch to measure execution times of code which takes milliseconds. This is ridiculous, it's like saying if you go out you gonna get killed because 1 on million is a murder. If we sum up all ticks form all iterations, and divide this by the number of iterations we get the average delta of 0.07 ticks!

The fact that staring and stopping the Stopwatch can take up to 6-7ms, once every few tens of millions of times, tells you exactly nothing. If you doing benchmarks and calculating averages, this peak will cause virtually no impact on the result. Sure, if you measure time of only a single call, which takes couple of milliseconds, then once every few tens of millions of times you can get some disturbing results (I wasn't able to reproduce such high peak by the way), but I don't believe anyone do such things.

What is really important is this average and the linked post actually convicted me that I indeed can rely on Stopwatch to measure more accurately then I originally thought.

**Comment by adamsitnik** [comment]
> What is really important is this average and the linked post actually convicted me that I indeed can rely on Stopwatch to measure more accurately then I originally thought

If this has solved your problem then I am closing the issue.
