### ISSUE TITLE
Include tested Generic parameter as column in various default outputs

### ISSUE THREAD

**Issue by damageboy** [dotnet/BenchmarkDotNet#1400]
The current output formats: Console, markdown, csv, html are all lacking the generic type parameter when exporting benchmarks that were configured with `[GenericTypeArguments]`.

This makes compiling combined reports needlessly more complicated.
For example, it would make sense to be enable merging the generated CSVs for all the generic types that were benchmarked and enable generating some sort of grouped visualization with a different tool.

I'm opening this issue to make sure I'm not missing something obvious about this.

If this is indeed the case, and there are no objections, I'll try to add such an output column be default and submit a PR.

Any thoughts?

**Comment by adamsitnik** [comment]
By default, BDN generates a single report per type. If given report belongs to one type, the type information is not included in the report because it's part of the file name.

I think that what you are looking for is the `--join` switch:

Sample benchmarks:

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace Generic
{
    class Program
    {
        static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);
    }

    [GenericTypeArguments(typeof(int))]
    [GenericTypeArguments(typeof(string))]
    public class Some<T>
    {
        [Benchmark] public bool IsValueType() => typeof(T).IsValueType;
    }

    [GenericTypeArguments(typeof(int))]
    [GenericTypeArguments(typeof(int))]
    public class Other<T> where T : new()
    {
        [Benchmark] public T Create() => new T();
    }
}
```

Sample command:

```cmd
dotnet run -c Release --filter '*' --join --job dry
```

Sample output:

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.100-preview.2.20119.13
  [Host] : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
  Dry    : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT

Job=Dry  IterationCount=1  LaunchCount=1  
RunStrategy=ColdStart  UnrollFactor=1  WarmupCount=1  

```
|         Type |      Method |     Mean | Error |
|------------- |------------ |---------:|------:|
| Other&lt;Int32&gt; |      Create | 391.7 us |    NA |
| Other&lt;Int32&gt; |      Create | 385.1 us |    NA |
|  Some&lt;Int32&gt; | IsValueType | 368.8 us |    NA |
| Some&lt;String&gt; | IsValueType | 378.4 us |    NA |

@damageboy if `--join` is not enough I am perfectly fine with including the type name as a new column

**Comment by damageboy** [comment]
No, I think it's good enough for me, Thanks!
