### ISSUE TITLE
Controlling host exe name

### ISSUE THREAD

**Issue by ryanmolden** [dotnet/BenchmarkDotNet#1468]
Couldn't find this in the documents. 

1) Is it possible to NOT have the benchmark runner be a randomly named exe (some GUID)? It would make debugging failures that only happen in benchmarks a LOT easier if it had a predictable name so I could use something like procdump to capture exceptions.

**Comment by adamsitnik** [comment]
Hi @ryanmolden 

We use random names to avoid files in use exceptions which in the past were very often caused by various anti-virus software (that was scanning the `.exe` while we were trying to remove it after running the benchmarks).

To differentiate the benchmarks we pass `--benchmarkName` argument to the process:

```log
// Execute: C:\Projects\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\bin\Release\net461\594aa796-d4c7-4bb6-8bfd-a6cf7ea74937.exe --benchmarkName "BenchmarkDotNet.Samples.IntroBasic.Sleep" --job "Default" --benchmarkId 0 in
```

And print PID when it quits:

```log
// AfterAll
// Benchmark Process 26608 has exited with code 0
```

If this is not enough, you can use `Job.WithId(string)` method to give Job an ID and combine it with `KeepBenchmarkFiles` method. This will make BDN use provided ID as exe name. But it will also make BDN keep the auto-generated files after running the benchmarks.

```cs
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;

namespace BenchmarkDotNet.Samples
{
    public class Program
    {
        public static void Main(string[] args) 
            => BenchmarkSwitcher
                .FromAssembly(typeof(Program).Assembly)
                .Run(args, DefaultConfig.Instance.AddJob(Job.Default.WithId("name")).KeepBenchmarkFiles());
    }
}
```

I know that it's far from perfect, but this is the best thing we can offer.

Thanks,
Adam
