### ISSUE TITLE
docs: Getting started guide

### ISSUE THREAD

**Issue by steveoh** [dotnet/BenchmarkDotNet#1474]
Do you think it makes sense to swap the current getting started guide 1 and 2. It seems that the package should be installed into the console application.

**Comment by adamsitnik** [comment]
@steveoh you are right, the doc should mention creating a console app before installing the NuGet package

would you be interested in sending a PR? the file is here: https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/guides/getting-started.md

**Comment by michalgalecki** [comment]
I tried to send PR but I'm not sure if i did it correctly. It's my first PR ever.

**Comment by adamsitnik** [comment]
Hi @michalgalecki 

Thank you for your help!

You have opened the PR against your fork, while you should have opened it against the upstream repo (https://github.com/dotnet/BenchmarkDotNet in our case)

When you want to send a PR, you should push changes to a branch of your fork (you have done that) and after you do it, when you go to the upstream repo page you should see a new green button "Compare  & Pull Request" like this:

![obraz](https://user-images.githubusercontent.com/6011991/96882079-35be5400-147f-11eb-9bc9-28bce1722b7a.png)

This magic button is visible only for some time after you push the changes so you won't see it now unless you push something to your branch again.

Since the magic button is gone, you need to do the following:

Go to https://github.com/michalgalecki/BenchmarkDotNet/pulls and click "New Pull Request" button:

![obraz](https://user-images.githubusercontent.com/6011991/96882942-1d026e00-1480-11eb-9049-a3e948198f3d.png)

Chose the branch of your fork:

![obraz](https://user-images.githubusercontent.com/6011991/96883142-5a66fb80-1480-11eb-9c0d-b66b91b3ee6c.png)

and press the "Create Pull Request" button.

**Comment by michalgalecki** [comment]
Right, I thought that something went wrong. Now PR should be fine.
Thanks for the guide!
