### ISSUE TITLE
Why was the printIL option removed?

### ISSUE THREAD

**Issue by castholm** [dotnet/BenchmarkDotNet#1522]
Earlier this year I was using BenchmarkDotNet (v0.12.0) as a tool to quickly and easily inspect both the IL and the JITted asm of certain parts of one of our code bases. However, this option appears to be absent in the most recent version (v0.12.1).

Why was `printIL` removed? Is it gone for good or are there any plans to reintroduce it along the line? If not, what alternative tools or frameworks would you recommend if I want a quick way to compare the C# source, IL and JIT asm?

(Additionally, [the disassembler documentation on the website](https://benchmarkdotnet.org/articles/features/disassembler.html) hasn't yet been updated to reflect the new configuration options.)

**Comment by adamsitnik** [comment]
Hi @castholm 

> Why was `printIL` removed?

In https://github.com/dotnet/BenchmarkDotNet/pull/1332 I've rewritten the disassembler. My goal was to make it cross-platform and more reliable.

To be able to print the IL we had to read the assembly definition. This was not always possible (some assemblies are precompiled or you simply can't access them) and was sometimes causing errors.

Moreover, ClrMD which is a crucial part of the disassembler is using a different way of identifying methods (example: one was using `/` for nested types, the other was using `+`). This was forcing us to maintain mappings between these two. Over time, the mappings turned out to be flaky. 

Since printing `IL` was not a frequently used feature, I decided to give up on it and remove it.

> Is it gone for good or are there any plans to reintroduce it along the line? 

I definitely don't plan to reintroduce it (due to complexity).

> what alternative tools or frameworks would you recommend if I want a quick way to compare the C# source, IL and JIT asm

https://github.com/0xd4d/dnSpy should be able to give you C#, ASM, and IL.

You can also use https://sharplab.io/ which is a very user-friendly web-based application.

>  the disassembler documentation on the website hasn't yet been updated to reflect the new configuration options.

thanks for pointing this out, I am going to send a fix this week and the website is going to get updated with the next release

**Comment by adamsitnik** [comment]
It looks like docs were updated in https://github.com/dotnet/BenchmarkDotNet/pull/1463 and the website is going to be updated with the next version release.

I am going to close the issue, please feel free to ask more questions.
