### ISSUE TITLE
How to benchmark cross-process throughput?

### ISSUE THREAD

**Issue by astef** [dotnet/BenchmarkDotNet#1531]
I'd like to measure the performance of the code, which is mainly responsible for cross-process communication. E.g. https://github.com/Kittyfisto/MMQ

To achieve that, I need at least two processes to be run during benchmark.

I want to measure the throughput of this channel, i.e. the number of messages I would be able to transfer from process A to process B per one second.

Is it possible with BenchmarkDotNet? Is it even in the scope of this library, or I should go with my own solution?

**Comment by adamsitnik** [comment]
Hi @astef 

BenchmarkDotNet was designed for very accurate micro-benchmarking. All the metrics that we report are specific to the process which is executing the benchmark. The architecture does not have a concept of multiple processes like client and server.

You could use BDN to:

* start the B process in the `[GlobalSetup]` method
* send messages from benchmarking process (process A) to process B as part of the `[Benchmark]` method

But the time reported by BDN would be an average time for sending a single message and how much memory the process A allocated to do that. BDN would not capture any information about the other process (B). Last but not least, BDN runs the benchmarks sequentially, so it's very likely that you would not be able to achieve 100% CPU consumption. 

An alternative would be to use https://github.com/aspnet/Benchmarks/ which has a client-server concept and can track metrics for both. But it was designed to run web server benchmarks, so I am not sure if this would be a perfect fit for your need.

You might need to ask this question at Stack Overflow, where someone could point to you to a different harness that was designed to solve such problems.

Since there is nothing actionable on our side here, I am closing the issue.

Thanks,
Adam
