### ISSUE TITLE
Automatically continue from crashed benchmark

### ISSUE THREAD

**Issue by timcassell** [dotnet/BenchmarkDotNet#1557]
I have some benchmarks which crash with some parameters, and that's okay for what I'm trying to test. What's annoying about it, though, is that windows 7 has the popup that I have to click to close the application for the other benchmarks to continue running. I know I can configure windows itself to always close unresponsive applications, but I was wondering if I could do that just for the benchmarks?

**Comment by adamsitnik** [comment]
Hi @timcassell 

BenchmarkDotNet runs every benchmark in a stand-alone process and executes the code in a try-catch block:

https://github.com/dotnet/BenchmarkDotNet/blob/10abc4f4daa5142f0257c9d512a38afc2ab28be1/src/BenchmarkDotNet/Templates/BenchmarkProgram.txt#L55-L72

For all the exceptions that can be caught, the text is printed to console and `-1` is returned as process exit code.

If you are still getting an error and a popup from Windows OS I am afraid that there is nothing we can do about it. The exception either can not be caught (`StackOverflowException, `AccessViolationException` etc) or you have some local settings that affect that. Since we can't change it on BDN side I am closing the issue.
