### ISSUE TITLE
[Docs] Update Console Args doc

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1559]
The doc that describes the usage of console args which is available at https://benchmarkdotnet.org/articles/guides/console-args.html

is a little outdated. It would be great if someone could update it and sync with the code: add missing arguments, apply the renames.

Example: the doc mentions `--cliPath` while we have renamed it to `--cli` some time ago.

The source is available here: https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/guides/console-args.md

**Comment by kevinsalimi** [comment]
Hello Adam,
I would like to contribute and update the doc if still possible.

**Comment by adamsitnik** [comment]
@kevinsalimi great! I've assigned you. Please let me know if you need any help

**Comment by kevinsalimi** [comment]
Evening Adam,

So far, I've updated the doc and also add the new ones base on the code.
But I've an ambiguity regarding some new args. Since I'm new in the project, realization of some args are not easy for me in order to categorize them in an appropriate category.

For example: `--strategy`
I couldn't figure out, whether it depends on an exist category or should be added at the end of the More part?

Have you any idea in the cases like this?
Thank you.

**Comment by kevinsalimi** [comment]
Hello @adamsitnik,
Could you please help me on this? 
If my question is not clear let me know please. 😊
Thank you.

**Comment by adamsitnik** [comment]
> I couldn't figure out, whether it depends on an exist category or should be added at the end of the More part?

@kevinsalimi please excuse me for the delay. I think that it's OK if you add everything that you are not sure of to the More part

**Comment by kevinsalimi** [comment]
It's OK. thank you.
