### ISSUE TITLE
Measure pooled objects memory

### ISSUE THREAD

**Issue by timcassell** [dotnet/BenchmarkDotNet#1579]
I love the fact that I can see how much memory is allocated on each run with the MemoryDiagnoser. What I'm missing, though, is measuring the difference in memory before a benchmark, and after (i.e. how much memory is perpetually consumed from pooled objects). Is there a way I can measure this now?

**Comment by adamsitnik** [comment]
Hi @timcassell 

> Is there a way I can measure this now?

To get this detailed information you need to use a memory profiler.

The memory profilers that I can recommend:
* [Visual Studio Memory Profiler](https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage-without-debugging2?view=vs-2019)
* [dotMemory](https://www.jetbrains.com/dotmemory/)
* [.NET Memory Profiler](https://memprofiler.com/)

Once you choose the one that you like, you need to:

* take a memory snapshot of your app (using the profiler)
* perform the operation that you want to investigate
* take another memory snapshot
* use the profiler to show you the diff between two snapshots

By doing this you will get all the objects that have been allocated and survived the cleanup (like caches etc). This is also the way of finding memory leaks ;)

Since this is a memory profiler feature and we don't plan to add it to BenchmarkDotNet, I am going to close the issue.

Thanks,
Adam

**Comment by timcassell** [comment]
Hm, I was hoping to be able to add it to the summary table. It seems I can get the data in code through the process (GlobalSetup/GlobalCleanup seem like good places to do it)... is there a mechanism to add custom data to the summary table? It would be nice to have that happen automatically rather than manually doing it for each run.

**Comment by adamsitnik** [comment]
In this particular case, you would need to implement your own diagnoser. You can use [EtwProfiler](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Diagnostics.Windows/EtwProfiler.cs) as an example.

In other cases, you could implement a custom column: https://benchmarkdotnet.org/articles/configs/columns.html#custom-columns
