### ISSUE TITLE
Is there  a way to measure performance in a hardware-independent way?

### ISSUE THREAD

**Issue by pawelpabich** [dotnet/BenchmarkDotNet#1588]
Hey,

It's not easy to run a perf benchmark in an isolated environment that is hosted in one of the main Cloud providers. 2 VMs of the same size can yield vastly different performance.  

My goal is to make sure that an existing piece of code doesn't suddenly become much slower.  One way to solve this problem would be to measure perf using a unit that is hardware-independent?  Doest Benchmark.NET  support something like that? Am I dreaming :)?  

I had a look at [Hardware Counters](https://adamsitnik.com/Hardware-Counters-Diagnoser/) but I haven't found anything there that would solve my problem.

**Comment by adamsitnik** [comment]
Hi @pawelpabich 

> Doest Benchmark.NET support something like that?

It does not. 

> measure perf using a unit that is hardware-independent

My current best idea is to get the assembly code and use an emulator that assigns a hardware-independent cost to every instruction. I've heard of such systems, but never used them myslef. It's also defnitely not on our TODO list (too big and too complex for an OSS benchmarking tool)

> I had a look at Hardware Counters

You could use the number of Instructions Retired, but I am not sure if this would be an apples to apples comparison when two VMs would have major hardware differences.

You can always just... run the benchmarks twice. Once without given change, and once with the change and do A vs B comparison. This should always work, but would require twice the time.

Since there is nothing actionable on BDN side, I am going to close the issue.

Thanks,
Adam

**Comment by pawelpabich** [comment]
Thanks for the ideas. I will give them a try and see where I end up.
