### ISSUE TITLE
Is there a way to disable a benchmark?

### ISSUE THREAD

**Issue by silkfire** [dotnet/BenchmarkDotNet#1589]
Does there currently exist functionality to preventing invididual benchmarks from running, say with an attribute or a flag, instead of having to comment them out in code?

**Comment by adamsitnik** [comment]
Hi @silkfire 

No, but you can use filters to choose which benchmarks you want to run by using `--filter` console line argument:

https://benchmarkdotnet.org/articles/guides/console-args.html#filter

If `--filters` is not enough you can implement your own filter: 
* [doc](https://benchmarkdotnet.org/articles/configs/filters.html) 
* [sample](https://github.com/dotnet/performance/blob/master/src/harness/BenchmarkDotNet.Extensions/OperatingSystems.cs)

Since we don't plan to change that, I am going to close the issue.

Thanks,
Adam
