### ISSUE TITLE
WASM benchmark fails with circular dependency error

### ISSUE THREAD

**Issue by MorganR** [dotnet/BenchmarkDotNet#1597]
Hello, I'm trying to run a WASM benchmark, and I'm running into a Circular dependency error: 

```
BenchmarkDotNet.Autogenerated.csproj(27,11): error MSB4006: There is a circular dependency in the target dependency graph involving target "Publish".
Build FAILED.
```

Command to run the benchmarks:

```
dotnet run -c Release -- --runtimes Wasm --cli ${PATH_TO_RUNTIME}/dotnet.sh --wasmMainJs ${PATH_TO_RUNTIME}/src/mono/wasm/runtime-test.js --iterationCount 5 --warmupCount 1
```

Interestingly, this runs two sets of benchmarks, one in the host environment (.NET 5, x64), and then one in WASM. I would have expected just the WASM benchmarks to run. The host benchmark succeeds, but then the WASM run results in the error above.

This is part of an open source project, so you can find the whole repo [here](https://github.com/MorganR/SudokuSpice). My dotnet runtime is synced to the commit tagged as the .NET 5 RTM release (tag: v5.0.0-rtm.20519.4). I've confirmed I can successfully build a Wasm runtime using `./build.sh --os Browser -c Release --arch wasm`.

**Comment by adamsitnik** [comment]
Hi @MorganR 

I know that @naricc has hit this error in the past and reported it in the dotnet/performance repo: https://github.com/dotnet/performance/issues/1518

@MorganR  Could you please try the workaround suggested there? (`This error doesn't occur if a custom runtime pack is specified with --customRuntimePack `)

@naricc did you find any solutions to that?

> Interestingly, this runs two sets of benchmarks,

this happens because of the `SimpleJob` attribute that you are using for all the three types that define benchmarks:

https://github.com/MorganR/SudokuSpice/blob/0475b34571ca4767e1b673318712e1dcf82a00b1/SudokuSpice.Benchmark/CsvBenchmarker.cs#L9
https://github.com/MorganR/SudokuSpice/blob/0475b34571ca4767e1b673318712e1dcf82a00b1/SudokuSpice.Benchmark/PuzzleBenchmarker.cs#L11
https://github.com/MorganR/SudokuSpice/blob/0475b34571ca4767e1b673318712e1dcf82a00b1/SudokuSpice.Benchmark/GeneratorBenchmarker.cs#L11

BenchmarkDotNet runs every benchmark for every job defined in the config. Here you defnie one job via the attribute and another via command line arguments and as a results you get two jobs and the benchmarks are run twice

**Comment by naricc** [comment]
I've put a low priority on that issue (https://github.com/dotnet/performance/issues/1518) because almost every one has been using the --customRuntimePack option, but if that doesn't work for your scenario I can try to get to it sooner.

**Comment by MorganR** [comment]
Thank you folks! That worked. To clarify a bit more for others, the full flag looks like this:

```
--customRuntimePack ${PATH_TO_RUNTIME}/artifacts/obj/browserwasm.Release/Microsoft.NETCore.App.Runtime/layout/runtime/packs/Microsoft.NETCore.App.Runtime.browser-wasm/5.0.0
```

Note I assume you have to build a release WASM runtime in order for this to be present.
