### ISSUE TITLE
Don't display Job and Toolchain column when running benchmarks for multiple runtimes

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1603]
The `Job` and `Toolchain` columns are redundant, `Runtime` is all we need:

![obraz](https://user-images.githubusercontent.com/6011991/99952390-defab180-2d7f-11eb-851c-ffef6fbb0647.png)

I see this very often when our users are presenting BDN results at conferences|meetups etc

The `Job` column should remain visible when the user has set the Job id in explicit way.

/cc @stephentoub

**Comment by marcnet80** [comment]
Hello, @adamsitnik, please review PR.
Thanks.

**Comment by kevinsalimi** [comment]
What's the status for this?

**Comment by lipchev** [comment]
This would indeed be very helpful- it is just the amount of space my reports need in order to avoid line wrapping..

Additionally I think the same logic applies to the rplot build script. My customization of it, simply replaces all occurrences of `Job_Id` with `Job_Runtime` making for a much more useful legend (although Job_Toolchain is also a good option- if you don't want to have white spaces in the file name)

**Comment by jkrueger721** [comment]
Is this still open?

**Comment by kevinsalimi** [comment]
> Is this still open?

From that time onward, unfortunately, I couldn't spend time on this issue. If you can, please go ahead.
Thank you for your help.

**Comment by jkrueger721** [comment]
@adamsitnik I would like to take over this issue.

**Comment by adamsitnik** [comment]
Fixed by #1621
