### ISSUE TITLE
[QUESTION] Benchmark inlining but different results

### ISSUE THREAD

**Issue by PrimoDev23** [dotnet/BenchmarkDotNet#1619]
Hello guys,
I just want to ask a question in terms of inlining and benchmark.net

I have benchmarked a different way for string.IsNullOrEmpty (See code below)
Now I have discovered that this code

![image](https://user-images.githubusercontent.com/46970398/102331383-11688a80-3f8b-11eb-951b-6cbb98979813.png)
(around 27ns)

is faster compared to this one

![image](https://user-images.githubusercontent.com/46970398/102331418-1f1e1000-3f8b-11eb-9c01-10b97eaa4544.png)
(around 80ns)

Ofcourse there is another function call that could lead to different results, but after checking inline on both

![Code 1](https://user-images.githubusercontent.com/46970398/102330171-85099800-3f89-11eb-8ba4-7b54b2fca7e9.png)

![Code 2](https://user-images.githubusercontent.com/46970398/102331102-aa4ad600-3f8a-11eb-95e8-9860059ed5d7.png)

I saw that actually both are inlined the same way and would theoretically produce the same code after ebing compiled.
So I hope you can answer my question why I am still getting different results with theoretically the same code.

Sincerely,
PrimoDev

**Comment by adamsitnik** [comment]
Hi @PrimoDev23 

The best way to find out why it happens is to use [DisassemblyDiagnoser](https://adamsitnik.com/Disassembly-Diagnoser/) and compare the produced assembly code. 

In the code that you have provided the JIT might replace the loop with a const due to constant folding. You should avoid loops in your benchmarks, you can read more about it [here](https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md#Loops)

BenchmarkDotNet prevents the `[Benchmark]` method to be inlined, but it can't prevent JIT from detecting that given field is not changing. To solve this problem, you can pass the argument to benchmark via  `[Arguments]` attribute:

```cs
[Arguments("notEmpty")]
[Arguments("")]
[Arguments(null)]
[Benchmark(Baseline=true)]
public bool IsNullOrEmpty(string value) => string.IsNullOrEmpty(value);

[Arguments("notEmpty")]
[Arguments("")]
[Arguments(null)]
[Benchmark]
public bool Custom(string value) => value?.Length > 0;
```

https://benchmarkdotnet.org/articles/features/parameterization.html#sample-introarguments

**Comment by adamsitnik** [comment]
Since there is nothing actionable on BDN side, I am going to close the issue. @PrimoDev23 please feel free to reopen it if my answer was not enough.
