### ISSUE TITLE
BenchmarkDotNet stuck because of the .log file

### ISSUE THREAD

**Issue by Pepo-BG** [dotnet/BenchmarkDotNet#1642]
Hello,
I run some benchmarks for my DB, but at some point, the PC lost connection to the SQL Server. Because of that, the BenchmarkDotNet.log file started logging messages like `A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.)`.  The .log file has 212000 lines and 44 MB. Unfortunately, the Benchmark stucks and I believe the reason is the size of the log file (it was modified 5 hours ago).
My question is - can I resume the Benchmark? I tried to remove these messages from the log, to rename it or even delete it, but the .log file is locked and I can't do that.

If I kill the process (the GUID process generated by the BenchmarkDotNet), will the whole benchmark be terminated? If so - Can I extract the Benchmark summary from the log file?

Thanks!

**Comment by adamsitnik** [comment]
Hi @Pepo-BG 

> Because of that, the BenchmarkDotNet.log file started logging messages like

BenchmarkDotNet does not know anything about your benchmark. If your benchmark is writing anything to console, BDN just writes it to the log. However, if your benchmark writes to standard error (`Console.Error`) it might get stuck due to #1629 which already got fixed in #1631 but have not been released to nuget.org yet (a matter of a few weeks from now)

> the Benchmark stucks and I believe the reason is the size of the log file

it's very unlikely as we have more than 3000 benchmarks in https://github.com/dotnet/performance/tree/master/src/benchmarks/micro and the produced log files are much bigger

If you want to find out why it go stuck, you should attach a debugger and see what's going on.

> My question is - can I resume the Benchmark?

**Comment by adamsitnik** [comment]
I believe that I've answered all your questions. Since there is nothing actionable on our side, I am going to close the issue.

If you attach a debugger and validate that even with a [preview version](https://benchmarkdotnet.org/articles/guides/nuget.html#nightly) of BDN you can get the benchmark stuck, please feel free to provide a minimum repro case and reopen the issue. Thanks!

**Comment by Pepo-BG** [comment]
Thank you, @adamsitnik for your help! Very helpful links!
About my case - when I killed the process - the running benchmark failed and BDT continued.
