### ISSUE TITLE
Determine the best method to call when that method is expected to run only once (or a very limited number of times)

### ISSUE THREAD

**Issue by netcorefan1** [dotnet/BenchmarkDotNet#1660]
Hello to all,
I am very new to BDN, therefore please accept my apologies if what I'm assuming is wrong.
From what I understand the library is meant to measure performance on heavy load scenarios.
However I often find myself in situations where I would like to know if a method may bring more benefits over another when I expect that method to run only once (or a very limited number of times). 
Supposing that I expect to call the method `GetData()` only once or a couple times. Inside that method I need to access and do some operations on some buffers and I am undecided between a regular array, an ArrayPool, a MemoryPool or Span:

```
// Sample shows only one buffer type for simplicity, but I may be need to create and access a couple of more
// Data processing along with many other operation omitted
public MyData GetData()
{
    // Option 1
    int[] array = new int[len];

    // Option 2
    var pool = ArrayPool<int>.Shared;
    int[] array = pool.Rent(len);
    pool.Return(array);

    // Option 3
    using var rent = MemoryPool<int>.Shared.Rent(len);

    // Option 4
    var spanArray = new int[len].AsSpan();
}
```

A normal benchmark where I can check performance based on array lenght should look like this:
```
[MemoryDiagnoser]
public class MyBenchmark
{
    private const int len = 100;
    [Benchmark(Baseline = true)]
    public void RegularArray()
    {
        int[] array = new int[len];
    }
    [Benchmark]
    public void SharedArrayPool()
    {
        var pool = ArrayPool<int>.Shared;
        int[] array = pool.Rent(len);
        pool.Return(array);
    }
    [Benchmark]
    public void SharedMemoryPool()
    {
        using var rent = MemoryPool<int>.Shared.Rent(len);
    }

    [Benchmark]
    public void SpanArray()
    {
        var spanArray = new int[len].AsSpan();
    }
}

...and will give me the following result where I can clearly see what is the best choice in terms of speed, memory allocation etc:

|           Method |      Mean |     Error |    StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |----------:|----------:|----------:|------:|--------:|-------:|------:|------:|----------:|
|     RegularArray | 179.36 ns | 423.50 ns | 23.213 ns |  1.00 |    0.00 | 0.2702 |     - |     - |     424 B |
|  SharedArrayPool |  72.22 ns | 123.90 ns |  6.792 ns |  0.41 |    0.08 |      - |     - |     - |         - |
| SharedMemoryPool | 111.09 ns |  59.06 ns |  3.237 ns |  0.63 |    0.09 | 0.0153 |     - |     - |      24 B |
|        SpanArray | 201.91 ns | 433.01 ns | 23.735 ns |  1.14 |    0.22 | 0.2702 |     - |     - |     424 B |
```

(_SpanArray result here does not make much sense, but I have included it in `GetData()` anyway where, for simplicity, I voluntarily omitted how the data is processed once I get the buffers. **When I run benchmarks I always mean to include data processing** and is where I expect SpanArray to return results that make sense_)

I see from the log lot of iterations and operations happening inside the hood and I suppose the above table only applies to intensive usage of these methods.
However in the case that I expect `GetData()` to run only once or a couple of times, the above table will not help because I suppose it only applies to hundreds of iterations, but when expected usage is very "light", what the table shows a method to be the more performant could be the less performant.

So, my question is, what would be (supposing is possible) the correct configuration to use in those cases?
The sample code applies to Arrays and Span, but it can be of any type and I am referring to a general solution. Also, inside the target method (`GetData()` in the specific sample) I need to end up with a result that includes every operation that happens inside that method based on the type of implementation (RegularArray, SharedArrayPool etc).

Thanks

**Comment by adamsitnik** [comment]
> I see from the log lot of iterations and operations happening inside the hood and I suppose the above table only applies to intensive usage of these methods.

In case you want to specify the number of invocations in an explicit way, you should read the [how it works](https://benchmarkdotnet.org/articles/guides/how-it-works.html) doc to get a good understanding of what you can configure and use one of the config options [1](https://benchmarkdotnet.org/api/BenchmarkDotNet.Attributes.SimpleJobAttribute.html#BenchmarkDotNet_Attributes_SimpleJobAttribute) [2](https://benchmarkdotnet.org/api/BenchmarkDotNet.Jobs.JobExtensions.html#BenchmarkDotNet_Jobs_JobExtensions_WithInvocationCount_BenchmarkDotNet_Jobs_Job_System_Int32_)


> However in the case that I expect GetData() to run only once or a couple of times, the above table will not help because I suppose it only applies to hundreds of iterations, but when expected usage is very "light", what the table shows a method to be the more performant could be the less performant.

It depends on which .NET Runtime you are going to use. In .NET Core 3.1+ you might be right, as [Tiered JIT](https://devblogs.microsoft.com/dotnet/tiered-compilation-preview-in-net-core-2-1/) was enabled by default. To tell the long story short, it counts how many times the given method was invoked and if it was invoked more than 30 times or it contains a loop, and there were no new methods compiled for 100ms and the app is not 100% busy it's going to promote given code from Tier 0 to Tier 1 and apply all optimizations. If not, you are executing Tier 0 code in production while comparing Tier 1 in benchmarks.

> So, my question is, what would be (supposing is possible) the correct configuration to use in those cases?

You should rather reverse the process:

* prepare a set of scenarios that are important to your product
* set measurable performance goals for each of the scenarios
* profile them using a profiler
* identify performance bottlenecks
* write a microbenchmark for each bottleneck 
* repeat until you meet the goal:
   * optimize the code based on what you find in the profiles
   * run unit tests to ensure the code is still valid
   * run microbenchmarks to see if your changes have improved perf

An example could be that you find that allocating new arrays in one particular method is a performance bottleneck and you switch to `ArrayPool` and use benchmarks to verify that the performance has improved. But very likely you may find out that the performance bottleneck is in a completely different place that did not look suspicious when you were just reading the code.

Since there is nothing actionable on BDN side, I am going to close this issue,
