### ISSUE TITLE
System.ValueTuple dependency is causing versioning issues after updating to NetStandard/NetCore

### ISSUE THREAD

**Issue by nicosijtsma** [dotnet/BenchmarkDotNet#1687]
https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/src/BenchmarkDotNet/BenchmarkDotNet.csproj#L26

As System.ValueTuple is part of the .NET 4.7 and .NET Standard framework, it should not be necessary to reference the package in the project

Our projects are reporting below warning
Warning MSB3277: Found conflicts between different versions of "System.ValueTuple" that could not be resolved. 

This should be resolved by removing the System.ValueTuple NuGet dependency from the package.

**Comment by adamsitnik** [comment]
We had a lot of issues with similar .NET Standard dependencies in the past. (https://github.com/dotnet/BenchmarkDotNet/issues/667, https://github.com/dotnet/BenchmarkDotNet/issues/895, https://github.com/dotnet/BenchmarkDotNet/issues/1160)

They were all caused by VS which was generating wrong assembly binding redirects. The solution was to just remove what the VS has generated. There is very little we can do about the VS, but if you are willing to send a PR and test it against:
* .NET 4.6.1 project using "classic" csproj
* .NET 4.6.1 project using "modern" csproj
* .NET Core 2.1

I am open to removing this dependency.
