### ISSUE TITLE
How to get process 'Max' memory usage for each method process by BenchmarkDotNet

### ISSUE THREAD

**Issue by shps951023** [dotnet/BenchmarkDotNet#1740]
Hi, @adamsitnik

Like visual studio debug diagnostic tools, it can know `max memory usage ` by chart
![](https://i.imgur.com/QTsXHSN.png)

I've tried [dotnet/BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) `MemoryDiagnoser` to get `Allocated`, but it's `all memory usage` not max memory usage.

```C#
    [MemoryDiagnoser]
    public class BenchmarkBase
    {
    
    }
```

Why I'd like to do it?    
Because I want to make sure that the maximum memory usage does not cause OOM  

Thanks!!

**Comment by joseftw** [comment]
I'm also interested in this :)

**Comment by timcassell** [comment]
`AppDomain` only exposes `MonitoringSurvivedMemorySize` and `MonitoringTotalAllocatedMemorySize`. I think you will have to petition https://github.com/dotnet/runtime/ to expose a `MonitoringMaximumMemorySize` to get that information.

**Comment by adamsitnik** [comment]
> Because I want to make sure that the maximum memory usage does not cause OOM

OOM can happen in multiple scenarios. Some of them:

- when your app has a memory leak. Detecting memory leaks isn't the job of micro benchmarking library. You need to use memory profiler to find leaks. 
- when your app has no leak, but there is not enough memory available at the system to satisfy the allocation needs (example: you web server suddenly gets a lot of web requests). This is dependent on your hardware and app traffic. In order to minimize chances for this happening you need to optimize your code to allocate as little as possible and the information exposed by `MemoryDiagnoser` should be enough to make it possible. Moreover, information provided by `MemoryDiagnoser` can be compared across various machines, while "max memory usage" would be machine-specific (on one machine GC might choose to allocate more memory until it performs cleanup, on another it may have less memory to use, perform cleanups more frequently and have lower max memory).

Since we don't plan to expose this infromation, I am going to close the issue. Thank you!
