### ISSUE TITLE
EventPipeProfiler: File names are very verbose

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/BenchmarkDotNet#1755]
I'm working to add event pipe profiling to benchmarks we use for NerdBank.GitVersioning: https://github.com/dotnet/Nerdbank.GitVersioning/pull/636.

The profile will generate files with names like this: _Nerdbank.GitVersioning.Benchmarks.GetVersionBenchmarks.GetVersionLibGit2(ProjectDirectory: "Cuemon")-.NET 5.0-20210728-183804.speedscope.json_ .

This causes a couple of usability issues:

- The file name contains a colon (:). While this is a valid character on Unix, I couldn't publish this file as an artifact in my Azure DevOps pipeline because DevOps refuses files which have a ':' in them. (I _assume_ this is because they reject any character which is not valid in an URL path)
- As a fallback, I archived all files as an `.tar.gz` archive, but the tar implementations on e.g. macOS don't handle file names which are longer than 255 characters very well. The file names are truncated. Because of this, some important details like the extension (.speedscope.json vs .nettrace) are missing.

So the gist is this:
- File names with unusual characters cause interoperability problems with tools (e.g. Azure DevOps)
- Long file names tend to get truncated, and important information then gets lost (like the filename).

You can argue that both issues are not a BenchmarkDotNet problem per se, but it would be great if the default configuration would not cause interoperability with commonly used tools in the ecosystem.

**Comment by adamsitnik** [comment]
> The file name contains a colon (:).

This was fixed by #1823 and is now part of 0.13.2 release.

> Long file names tend to get truncated, and important information then gets lost (like the filename).

We do our best, but sometimes the file names just have to get truncated.

The logic for choosing the trace file name can be found here:

https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Helpers/ArtifactFileNameHelper.cs

I am opened to any improvements (PRs).

Since the main issue was addressed (`:`) and I don't see a way of shortening the file names without loosing any information like namespace, type name, method name, argument values I am going to close the issue.
