### ISSUE TITLE
Exception thrown: 'System.IndexOutOfRangeException' in BenchmarkDotNet.dll

### ISSUE THREAD

**Issue by rlgordey** [dotnet/BenchmarkDotNet#1761]
Test runs through the initial iterations. But locks up and starts putting these Exception messages in the Debug Window.

Last Run Log file: [BenchmarkMethods.GetItemsClass-20210801-165808.zip](https://github.com/dotnet/BenchmarkDotNet/files/6913629/BenchmarkMethods.GetItemsClass-20210801-165808.zip)

 I can upload the whole project if needed.

**Comment by rlgordey** [comment]
When I turn on Just my Code in the Visual Studio Debugger options I don't get the error and the test runs ok.

**Comment by adamsitnik** [comment]
Hi @rlgordey 

These messages come from the code that you are trying to benchmark, not from BenchmakDotNet itself. You need to debug the process and figure out on your own what is wrong.

The easiest way to do that is to attach the debugger in setup method:

https://benchmarkdotnet.org/articles/guides/troubleshooting.html#launch-a-debugger-from-the-benchmark-process-using-debugger-api
https://benchmarkdotnet.org/articles/guides/troubleshooting.html#attach-a-debugger-from-ide

Since there is nothing actionable from BDN side, I am closing the issue
