### ISSUE TITLE
Start with simple usage of Benchmark 

### ISSUE THREAD

**Issue by Ohad29** [dotnet/BenchmarkDotNet#1830]
Hi , 
i am having issue with my application of timeout when using 3rd party library.
i would like to use benchmark to examine what is causing it.
is there is simple straight forward usage of Benchmark i can use ? start for example only with annotation ?

if you can point me to it...

Thanks

**Comment by adamsitnik** [comment]
Hi @Ohad29 

Benchmark can tell you how long does it take to execute given code, while a Profiler can tell you what took so long and where the time was spent exactly. This is why I would recommend you to use a CPU profiler instead of BenchmarkDotNet or any other benchmarking tool.

You can watch my conference talk where I've shared some of my thoughts on this subject: https://youtu.be/HDbtwTsar1Q?t=82

**Comment by Ohad29** [comment]
Hi ,

Thank you for your Replay !!!
it was recommended by the 3rd Party company to use the Benchmark but now i see you support only console application and we are WCF project :(
I am watching now your .net performance YouTube  and hope it will redirect me.
