### ISSUE TITLE
How to measure CPU usage on BenchmarkDotNet?

### ISSUE THREAD

**Issue by egvrcn** [dotnet/BenchmarkDotNet#1834]
I am using DotNet Benchmark and I can get the memory usage information as in the table below. But I need to access how much **CPU usage** is in the process I have done. Does DotNetBenchmark have this feature? If not, what method should I use?

|           Method |      Mean |     Error |    StdDev |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|----------------- |----------:|----------:|----------:|-----------:|----------:|----------:|----------:|
|  Get10000Records |  38.70 ms |  1.413 ms |  4.165 ms |  2000.0000 | 1000.0000 |         - |     12 MB |
| Get100000Records | 558.30 ms | 11.157 ms | 22.024 ms | 19000.0000 | 6000.0000 | 2000.0000 |    121 MB |

I asked the above question on stackoverflow.  Then I did research on hardwarecounters.  
I used this attributes for my benchmarks => [HardwareCounters(HardwareCounter.BranchMispredictions, HardwareCounter.BranchInstructions)]

But I can't see"Mispredict rate", "BranchInstructions/Op", "BranchMispredictions/Op" column in my results.

**Comment by YegorStepanov** [comment]
The benchmark program should be NET framework. Read comments [here](https://adamsitnik.com/Hardware-Counters-Diagnoser/).

Execute the net6.0 code like:
```
dotnet run -c Release -f net48 -- --runtimes net6.0
```

Don't forget about:
```xaml
<TargetFrameworks>net48;net6.0</TargetFrameworks>
```

I'm not tested it, but to execute `.NET Core` code you should use the preprocessor directives:

```C#
#if NET6_0_OR_GREATER
    var q = string.Create(...);
#endif
``` 

..

The diagnostic should be added here. I've spend a lot of time, read the Adam's blog few times, before I understand that I should download the old .NET.

..

I like the idea about `CPU usage`. UI performance can be measuring with this. 

If someone will use WinUI3, It's would be cool to have it, because WinUI3 [50-100 times](https://github.com/microsoft/microsoft-ui-xaml/issues/1633#issuecomment-968612478) slower then WPF. Good progress in 15 years.

**Comment by adamsitnik** [comment]
> Does DotNetBenchmark have this feature?

It does not, as it's more a profiler feature than micro-benchmarking library feature.

You can use `ETWProfiler` (windows) or `PerfCollectProfiler` (linux), open the trace file in PerfView and read this information. Docs: https://benchmarkdotnet.org/articles/features/etwprofiler.html
