### ISSUE TITLE
[Question/Proposal] Getting codegen only

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/BenchmarkDotNet#1837]
`DisassemblyDiagnoser` is an awesome thing. So is there a way to get the codegen without benchmarking the code itself? It should be more or less naive for .net <= 6, and for 6 it would be nice to be able to specify the tiers.

If there is no - I suggest it 😅

**Comment by adamsitnik** [comment]
Hi @WhiteBlackGoose 

BenchmarkDotNet is about benchmarking, disassembly is just an addition to it. You most likely need to use a stand-alone disassembler like https://github.com/0xd4d/JitDasm or build your own using https://github.com/icedland/iced/blob/master/src/csharp/Intel/README.md or a similar library.

Since we don't intend to add such a thing to BDN, I am closing the issue. Have a nice day!

**Comment by WhiteBlackGoose** [comment]
Hey, Adam. I see. Thanks for the answer

**Comment by WhiteBlackGoose** [comment]
For those curious, there's now a separate tool for it: https://github.com/WhiteBlackGoose/CodegenAnalysis
