### ISSUE TITLE
Add a "benchmark" cmd to dotnet

### ISSUE THREAD

**Issue by mattwarren** [dotnet/BenchmarkDotNet#213]
So it seems like you can [add extra commands](https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/Documentation/developer-guide.md#adding-a-command) to the dotnet tooling, how cool would it be to be able to do `dotnet benchmark`? 

This could then interact with the `BenchmarkSwitcher` so you can do `--class=Benchmarks`, `--diagnosers=Memory`, etc

From my understanding we would have to propose it as a [CLI issue](https://github.com/dotnet/cli/issues), but if we were serious about it, I think someone should do a proof-of-concept first.

Anyone agree? Anyone want to take it on?

**Comment by adamsitnik** [comment]
Good idea, but as for me I don't have time now.

**Comment by AndreyAkinshin** [comment]
An interesting post about the subj: https://surfingthecode.com/fun-with-global-tools-in-.net-core-2.1-preview/

**Comment by AndreyAkinshin** [comment]
The official documentation: https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools

**Comment by CodeTherapist** [comment]
I would like to do this.

**Comment by AndreyAkinshin** [comment]
@CodeTherapist, great!

**Comment by CodeTherapist** [comment]
@AndreyAkinshin, Done! At least a first version of it.

The tool supports the following syntax:

`
dotnet benchmarkdotnet [YourAssemblyFileWithBenchmarks.dll] [BenchmarkDotNet Arguments]
`

Maybe we could elaborate more features that would be useful.

Btw. I'm little bit confused because the [build](https://travis-ci.org/dotnet/BenchmarkDotNet/jobs/477069156#L5498) is failing.
I can't imagine how my change could break this test or did I missed something?

**Comment by adamsitnik** [comment]
@CodeTherapist this particular failure is not your fault, I am going to take a look into that failure to see what is going on

**Comment by adamsitnik** [comment]
Implemented in #1006
