### ISSUE TITLE
Root element is missing error

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/BenchmarkDotNet#2287]
I've been benchmarking some code for the past several weeks. I've been running benchmarks many, many times.

Then suddenly I tried to run it and now I get an error. I restarted Visual Studio but the error persists.

```
System.Xml.XmlException
  HResult=0x80131940
  Message=Root element is missing.
  Source=System.Private.Xml
  StackTrace:
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
```

Could I get some tips about what this error means and how one would go about trying to resolve it?

I'm running .NET 7 on Windows 10.

**Comment by AndreyAkinshin** [comment]
@SoftCircuits thanks for the report. Could you please provide more data so that we can investigate the problem? E.g., the full stacktrace of your exception?

**Comment by SoftCircuits** [comment]
@AndreyAkinshin So, the problem was that I have several configurations. And I was launching it with debugging. When I launch it without debugging, it works fine. Still, the error is not very meaningful to people who don't know the inner workings of the code.

Unfortunately, that is the entire contents of the Stack Trace.

**Comment by AndreyAkinshin** [comment]
1. At each moment the problem arises: at the start, in the middle of benchmarking, or at the end?
2. Could you try to wrap the main call of BenchmarkDotNet with a try-catch block and check if it is possible to gather the full stacktrace?

**Comment by SoftCircuits** [comment]
@AndreyAkinshin When the exception is thrown, Visual Studio takes me to this block of code starting at 265 in ExecutionContext.cs.

``` cs
ExceptionDispatchInfo? edi = null;
try
{
    callback.Invoke(state);
}
catch (Exception ex)
{
    // Note: we have a "catch" rather than a "finally" because we want
    // to stop the first pass of EH here.  That way we can restore the previous
    // context before any of our callers' EH filters run.
    edi = ExceptionDispatchInfo.Capture(ex);
}
```

Specifically, it takes me to the line `callback.Invoke(state);`.

For some reason, I cannot view the stack trace beyond what I've given you by looking at the exception details. But it this image shows the stack trace pane in Visual Studio.

![image](https://user-images.githubusercontent.com/3191331/224573374-e774e7a6-a766-49a1-a036-38f556127606.png)

**Comment by AndreyAkinshin** [comment]
It's a valid exception that is caught [here](https://github.com/dotnet/BenchmarkDotNet/blob/v0.13.5/src/BenchmarkDotNet/Toolchains/AppConfigGenerator.cs#L55). When you run your benchmarks without an attached debugger, it's properly handled. When you run it with an attached debugger, Visual Studio stops the execution when the exception happens. This behavior can be configured in the [VS settings](https://learn.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2022#tell-the-debugger-to-break-when-an-exception-is-thrown). To run the benchmarks with an attached debugger, you should uncheck `System.Xml.XmlException` so that VS doesn't stop your program.

Why do you want to run your benchmarks with an attached debugger? It's a non-recommended way since the debugger can significantly affect the measurements, and the obtained results cannot be trusted (and BenchmarkDotNet should warn you about it for an attempt to run benchmarks under debugging).

**Comment by AndreyAkinshin** [comment]
Resolution: it's a by-design behavior, there is nothing to fix on the BenchmarkDotNet side.
