### ISSUE TITLE
RPlotExplorer Plot with allocated memory.

### ISSUE THREAD

**Issue by osajdapawel** [dotnet/BenchmarkDotNet#2322]
Hello everyone.

Is there a way to configure **RPlotExplorer** to generate plots **with allocated memory**?

It generates beautiful charts with time, but I can't find any information about generating ones with allocated memory. Has anyone done it before?

Thanks in advance.

**Comment by AndreyAkinshin** [comment]
@osajdapawel Currently, such a feature is not supported. However, you can take the exported results (e.g., in the csv or json format) and build any charts you want using any plotting tools (including manual modification of the generated R script).

I do not plan to introduce configuration options for the `RPlotExporter` or evolve the script. This approach turned out to be too complicated for many users (it requires manual installation of R on the system) and too fragile (sometimes, it fails to download all the required packages). The long-term strategy is to introduce a better and more reliable plotting exporter (using 3rdParty plotting NuGet packages or via implementing our own plotting logic).
