### ISSUE TITLE
Include AVX512 in listed HardwareIntrinsics

### ISSUE THREAD

**Issue by stephentoub** [dotnet/BenchmarkDotNet#2388]
.NET 8 includes support for AVX512. `HardwareIntrinsics.GetFullInfo` should factor that in:
https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Portability/Cpu/HardwareIntrinsics.cs#L45-L91

**Comment by adamsitnik** [comment]
It should be very easy to implement, we just need someone with the AVX512 hardware to be able to test it.

**Comment by nietras** [comment]
Ah I think I get it, this is due to how I set this up perhaps, I use Params for parametizing the parsers to run, this list is then defined for "-f net8.0" then BDN runs each params for each runtime, but what and how it then uses the params for the Vector512 path on net7.0 runtime I do not know. I always struggle with BDN here since parametizing things at runtime is ... not easy.

I do not know how IndexOfAny then fails either but presumably this refers to "net8.0 version" of that code on net7.0 runtime then...
