### ISSUE TITLE
Autogenerated csproj targets the wrong Framework if GenerateAssemblyInfo is set to false

### ISSUE THREAD

**Issue by JoschiZ** [dotnet/BenchmarkDotNet#2422]
In solutions targeting `net7.0-windows `, when trying to run benchmarks the auto-generated `.csproj` targets `net7.0` instead of `net7.0-windows` if the benchmark `.csproj` includes  `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`.

**Comment by timcassell** [comment]
This is by design. We search the assembly for `TargetPlatformAttribute` to find the specific platform to use. If you specifically leave out that attribute by not generating assembly info, there's nothing we can do. You should either manually include the `TargetPlatformAttribute` yourself, or manually specify the toolchain in your job. See https://github.com/dotnet/BenchmarkDotNet/discussions/2408#discussioncomment-6754941
