### ISSUE TITLE
If a test run fails, the report shows it passed.

### ISSUE THREAD

**Issue by timcassell** [dotnet/BenchmarkDotNet#2520]
https://github.com/dotnet/BenchmarkDotNet/runs/20755135205
https://github.com/dotnet/BenchmarkDotNet/pull/2511/checks?check_run_id=21320355764

**Comment by AndreyAkinshin** [comment]
@timcassell thanks for the report! Indeed, this issue occurs from time to time (but not every time!) When I set up the test reports, I tried to handle this problem, but I failed. GitHub actions provide great capabilities for implementing "typical" workflows, but once you try to do something not-so-typical, problems appear. I will try to fix this problem myself when I have time. Meanwhile, if someone else wants to help, it would be much appreciated. The problem should be reproducible in BenchmarkDotNet forks.

**Comment by ketanpkolte** [comment]
Hi, I would like to work on this issue.

**Comment by timcassell** [comment]
@ketanpkolte Sure, I'll assign you. When you open the PR with the fix, please link to a failed run showing the report working correctly.

**Comment by ketanpkolte** [comment]
Hi @timcassell 
To bebug this issue, I made test name "BenchmarkDotNet.Tests.FolderNameTests.ToFolderNameStructTest" fail 
and removed windows test job because it was taking 40 minutes to run(will add back).
Updated run-tests.yaml and report-test-results.yaml to create unique artifact names and cleaned stale artifacts 
link to failed run: https://github.com/ketanpkolte/BenchmarkDotNet/runs/31691298016

![Image](https://github.com/user-attachments/assets/f0284333-17fc-47e8-8150-161c041aaa87)

**Comment by timcassell** [comment]
Awesome, nice work! Make sure to create a new branch before opening the PR (I saw you were working directly on master in your fork).
