### ISSUE TITLE
How best to specify that a Job should run quickly?

### ISSUE THREAD

**Issue by jcansdale** [dotnet/BenchmarkDotNet#257]
Hello,

I've just been using your FastAndDirtyConfig  example from here:
https://perfdotnet.github.io/BenchmarkDotNet/faq.htm

It doesn't seem to do much unless I include `Add(DefaultConfig.Instance)`:

``` c#
public class FastAndDirtyConfig : ManualConfig
{
    public FastAndDirtyConfig()
    {
        Add(DefaultConfig.Instance); // *** add default loggers, reporters etc? ***

        Add(Job.Default
            .WithLaunchCount(1)     // benchmark process will be launched only once
            .WithIterationTime(100) // 100ms per iteration
            .WithWarmupCount(3)     // 3 warmup iteration
            .WithTargetCount(3)     // 3 target iteration
        );
    }
}
```

Do you think this should be part of the sample?

**Comment by AndreyAkinshin** [comment]
@jcansdale, usually you have a set of configs which you can set on different levels (command line, BenchmarkRunner, specific Benchmark). You also can apply a set of configs for a single benchmark. For example, when you write
```cs
[ClrJob, CoreJob, MonoJob]
public class MyBenchmarks
```
you add 3 configs (each config contains only one job). Thus, `FastAndDirtyConfig ` adds `FastAndDirtyJob` for your benchmark. But you can combine it with any other configs, not only `DefaultConfig`. Maybe we should just introduce `[FastAndDirtyJob]` attribute. @adamsitnik, what do you think?

**Comment by jcansdale** [comment]
I'm still not completely clear how I would use the example `FastAndDirtyConfig` class.

Is this idea to use it like this?

```c#
            var config = new FastAndDirtyConfig();
            config.Add(DefaultConfig.Instance);
            BenchmarkRunner.Run(targetType, config);
```

Or is there a more concise way?

**Comment by AndreyAkinshin** [comment]
@jcansdale, the default way to mark the target benchmark class by this config:

```cs
[Config(typeof(FastAndDirtyConfig))]
public class MyBenchmarks
```

**Comment by jcansdale** [comment]
Ah, thanks! I was distracted by all the nice custom attributes and missed this fundamental one. :blush: 

I like your idea of creating `[FastAndDirtyJob]` custom attribute as part of the sample. This would make it very obvious how it how it can be used.

**Comment by jcansdale** [comment]
@AndreyAkinshin,

I'm working on integrating BenchmarkDotNet with TestDriven.Net and would like to understand how:

```
BenchmarkRunner.Run(targetType, config);
```

interacts with:

```
[ClrJob, CoreJob, MonoJob]
public class MyBenchmarks
```

Is there a way to force the following parameters on all of the `[ClrJob, CoreJob, MonoJob]` jobs?

```
            .WithLaunchCount(1)     // benchmark process will be launched only once
            .WithIterationTime(100) // 100ms per iteration
            .WithWarmupCount(3)     // 3 warmup iteration
            .WithTargetCount(3)     // 3 target iteration
```

Thanks for any pointers!

**Comment by AndreyAkinshin** [comment]
@jcansdale, here is a definition of `ClrJob`: https://github.com/PerfDotNet/BenchmarkDotNet/blob/v0.9.9/src/BenchmarkDotNet.Core/Attributes/Jobs/ClrJobAttribute.cs
You can define own config attribute which provides your own job or jobs (here is an example ofr 3 jobs: https://github.com/PerfDotNet/BenchmarkDotNet/blob/v0.9.9/src/BenchmarkDotNet.Core/Attributes/Jobs/AllJitsJobAttribute.cs) You can call it `MySuperConfig` and use it everywhere.

**Comment by jcansdale** [comment]
@AndreyAkinshin , Is there no way to override existing attributes when kicking off the benchmarking using `BenchmarkRunner.Run(targetType, config)`?

What I want to be able to do is quickly preview the benchmarks, not kick off a potentially long benchmarking session. For proper benchmarks, I'd close Visual Studio and run them from the command line using the original attributes. I don't want to force people to swap out the attributes when previewing. Does that make sense?

**Comment by AndreyAkinshin** [comment]
> Is there no way to override existing attributes when kicking off the benchmarking using BenchmarkRunner.Run(targetType, config)?

What exactly do you want to override?

> I don't want to force people to swap out the attributes when previewing.

We have `DryJob` for previewing. However, I think that the dry mode (or `FastAndDirty`) shouldn't be a default option. If user wants to preview benchmark results, the corresponded mode should be chosen manually.

**Comment by jcansdale** [comment]
> What exactly do you want to override?

If for example I target class with `[ClrJob, CoreJob, MonoJob]`, I'd like to make these jobs run with LaunchCount=1, IterationTime=100, WarmupCount=3 and TargetCount=3.

At a higher level, I don't want to accidentally kick off a benchmark that might take 20 minutes to complete (with no obvious way of stopping it). What would be the cleanest way to stop a benchmarking session? I've tried killing the parent process, but this seems to leave child processes behind.

I've tried to make it obvious what's going on by requiring the user to specify the config using an assembly attribute.

```
[assembly: BenchmarkTestRunner(typeof(FastAndDirtyConfig))]
```

That way they can easily do quick previews using TestDriven.Net and still do proper benchmarks from the command line (without fiddling with attributes).

I'd be interested if you have any thoughts on a better way to handle this?

**Comment by AndreyAkinshin** [comment]
> I've tried killing the parent process, but this seems to leave child processes behind.

Yeah, we don't have a managed API for that. In the console, I'm using Ctrl+C, it works fine. Probably we can add something like `CancellationToken` in the `Run` method. Can you create a separated issue about it?

> I'd be interested if you have any thoughts on a better way to handle this?

First of all, a user should specify initial set of jobs manually. There are a lot of different environments which could be targeted.

Right now I'm working on a new feature called `JobMutator` (it's a code name), it should be a part of `v0.9.10`. A `JobMutator` will be able to modify existed jobs (all of them or specific jobs). So, we can just add something like `DryJobMutator` in the config on the top level and make all the user jobs dry. I think, it should solve your problem. For example, you could create two run configuration: one for the original config and one for dry mode. I also recommend to add a warning which says that the observed results have pure accuracy level.

**Comment by jcansdale** [comment]
Would this allow me to do something like this:

```
BenchmarkRunner.Run(targetType, new DryJobMutator());
```

And have it run all of the attribute-specified jobs, but with Dry properties? That would be ideal. :smile:

The user could then specify:

```
[assembly: BenchmarkTestRunner(typeof(FastAndDirtyMutator))]
```

To let TestDriven.Net run an expediated benchmark on any of their benchmark classes/methods.

**Comment by jcansdale** [comment]
I look forward to trying it. :+1:

**Comment by jcansdale** [comment]
You've mentioned that defaulting to `FastAndDirtyJob` isn't a good idea. I've also read in the documentation:

> Usually, you shouldn't specify such characteristics like LaunchCount, WarmupCount, TargetCount, or IterationTime because BenchmarkDotNet has a smart algorithm to choose these values automatically based on recieved measurements.

Is there a better way to specify that a Job should run quickly or for a maximum duration that takes advantage of these smarts?

**Comment by AndreyAkinshin** [comment]
Unfortunately, it's almost impossible to run it quickly and get a good accuracy *at the same time in the general case*. You just don't know in advance what kind of problems you could get for a new benchmark. Right now you have the following ways:
* Use `DryJob` or `ShortRunJob` (a new brand for `FastAndDirty`) for a quick preview. These jobs are useful for verification (that you right a correct benchmark) and for getting first and very rough approximated results. I want also create a mutators for `DryJob` and `ShortRunJob` which can be easily applied for all user jobs.
* Use default job to get a good level of accuracy. (It takes some time)
* When you are playing with a benchmark for a long time and you are sure that there is no need to make a lot of iteration (because you have already seen many measurements), you can specify amount of iterations manually.

I totally understand that you want to have a magic way to quickly get a good results. But I still don't think that it's a good way when you are setting amount of iterations manually for each benchmark (or have a global "fast" config). There are always many questions in this case: why do you need exactly this number of iterations? Why your job has 10 iterations (not 9 or 11)?

The right question which you should ask is the following: what kind of trade-off between accuracy and benchmarking time do you want to achieve. Ideally, you should specify it on the API level. Probably, it will be a part of the `Job.Accuracy`. For example, now you can say: I want to get StandardError < 0.01 * Mean. It's a reasonable accuracy requirement because you usually don't care how much iterations will be performed (it's more about implementation details), you care about the accuracy level.

I want to have a way to request a specific level of accuracy (like Low/Medium/High, it could be a magic enum or a set of accuracy presets). Unfortunately, it's a really hard issue and it requests a lot of research. Also there is no a magic algorithm which will work fine for *all benchmarks in the world*. Hopefully, we can try to create a set of heuristics which works fine in 99% cases. =) Also I'm working on analyzers which can look at the current set of measurements and say something like "Hey, StdDev looks too big, probably your should do more iterations for this method". But all of it is "work in progress", I need much more time for that.

**Comment by jcansdale** [comment]
> Unfortunately, it's almost impossible to run it quickly and get a good accuracy at the same time in the general case. You just don't know in advance what kind of problems you could get for a new benchmark. 

I realize that BenchmarkDotNet has been designed to cater for a broad range of benchmarks - everything from a single IL operation something longer running that might even hit a database. The kind of scenario I'm thinking of is developers who may want to turn some of their unit tests into more formalized benchmarks.

I'm hoping to find some parameters that will make it useful in the majority of cases. Fast enough so that people don't mind running their benchmarks often, but not necessarily as accurate as they might want when running and keeping a history on their build server.

**Comment by AndreyAkinshin** [comment]
> when running and keeping a history on their build server.

Here you probably want to run performance tests, not benchmarks. We are working on BenchmarkDotNet as a performance (see https://github.com/PerfDotNet/BenchmarkDotNet/issues/155), but it's also "work in progress".

**Comment by bonesoul** [comment]
@jcansdale did you find a solution for using [ShortRunJob] with [CoreJob]
