### ISSUE TITLE
RISC-V support

### ISSUE THREAD

**Issue by frombingo** [dotnet/BenchmarkDotNet#2644]
Hello, All
Does anybody have tried to run this benchmark in RISC-V?
Is there  any plan for RISC-V ?

**Comment by adamsitnik** [comment]
Hi @frombingo 

It was not supported until you have asked for it. The fix was relatively simple: https://github.com/dotnet/BenchmarkDotNet/pull/2647

Once the PR gets merged and the CI passes you should be able to grab a preview package from our CI NuGet feed:

https://benchmarkdotnet.org/articles/guides/nuget.html?q=nightly#nightly

Please let me know if you run into any issues.
