### ISSUE TITLE
System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by SamuelCox** [dotnet/BenchmarkDotNet#333]
For no obvious reason, benchmarking my code produces this exception. As far as I can tell I am not doing anything wrong. Here's a gist to reproduce it: https://gist.github.com/SamuelCox/71e7467c32345eb984dbf1d75eeb199b

Seems similar to #104 

The code runs fine when not benchmarking it, also fwiw my code is pretty ugly because I was trying some things to get around the issue / figure out where the issue was.

**Comment by AndreyAkinshin** [comment]
Hi @SamuelCox,

I guess, you have this exception because of the `Console.WriteLine(n)` line. Now we are using console output to pass measurement values between benchmark and host processes. Several thoughts:
1. Using `Console.WriteLine` in the benchmark is a bad idea in general because it could be a bottleneck of you code.
2. If you really want to do it, you can try this workaround: `Console.WriteLine("// " + n)`. It should help, but it still doesn't make sense to me: I recommend you to rewrite your code without `Console.WriteLine`.
3. Probably, we will change our communication approach in the future. /cc @adamsitnik

**Comment by SamuelCox** [comment]
Ah ok, that makes sense. Yeah there's no reason for me to use that method, it was just a placeholder. 
Thanks!
