### ISSUE TITLE
Consider to disable MemoryDiagnoser by default

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#369]
Now we have cool `MemoryDiagnoser` which is great! However, it has one significant drawback: it noticeably increases total benchmarking time. For now, we don't have a nice API wich allows easily disable a diagnoser. I'm still working on it, I have some idea, but I'm not happy with them (thinking is in progress). So, I suggest to disable it by default. People who need the allocated memory column can easily enable it with `[MemoryDiagnoser]`. I also can highlight it in our documentation.

**Comment by adamsitnik** [comment]
@AndreyAkinshin I see your point. Maybe we should ask the users? What do you say for a twitter poll?

@mattwarren what are your thoughts?

**Comment by AndreyAkinshin** [comment]
I'm one of the users. In 95% of cases, I don't need the memory diagnoser. And when the results are almost ready, I have to wait additional time which is required for the diagnoser. It's very annoying.

**Comment by Mike-EEE** [comment]
Ah, this would introduce a breaking change wouldn't it?  Perhaps it is better to make this part of configuration somehow so that we're not forced to disable it via attributes.  Although I am not a fan of .NET configuration whatsoever, this is where app.config comes in handy.  .NET Core doesn't have an equivalent of this either, I don't think.

In any case, I think it is valuable to include by default, for the newbs such as myself that could learn a thing or two about memory. :)  But once you get an understanding of it (or are simply interested in speed), it would be nice to turn off for sure.

**Comment by AndreyAkinshin** [comment]
We have a lot of cool features which are disabled by default. I want to keep the default config as small as possible: only essential features should be enable. If you need a feature, you can enable it with a single line of code (the Overview section of the documentation should help you).
The diagnoser list is a part of our configuration, so you can controll it via attributes or via the object style. Also it's a typical situation when you want to apply different configuration for different benchmarks.

**Comment by mattwarren** [comment]
@AndreyAkinshin @adamsitnik As much as I love the `Memory Diagnoser`, I agree that having if off by default is the best choice.

x2 running time is a bit of a high price to pay for having in on OOTB.

**Comment by Mike-EEE** [comment]
Gotta say, sooooooo much nicer now. 👍
