### ISSUE TITLE
Discussion/Question: Visual Studio The Party Crasher

### ISSUE THREAD

**Issue by Mike-EEE** [dotnet/BenchmarkDotNet#370]
I actually have two questions here:

1. Is there a Gitter for this project?  [I found one in Gitter](https://gitter.im/PerfDotNet/BenchmarkDotNet) but it hasn't been updated since November.  Seems like this project would be much more active than that. :)
2. I've noticed that when I run my tests, BDN.Generated.exe loads up and so does Visual Studio.  It seems that VS is monitoring processes to attach, perhaps? It's taking about .5-1% of my CPU, and I would like to turn this off if at all possible.  Closing VS seems to yield another 1-2us in my results, but closing and restarting is _such_ a pain.  

The headscratcher here of course is that I am running a console window, and executing code that is compiled in release mode.  So it doesn't seem that this should involve VS at all.

Thank you in advance for any assistance you can provide.

**Comment by AndreyAkinshin** [comment]
1. Yes: https://gitter.im/dotnet/BenchmarkDotNet , you can find this link on our README page: https://github.com/dotnet/BenchmarkDotNet (one of the green badges). The old one is obsolete because we moved the BenchmarkDotNet project from the PerfDotNet organization to the dotnet.
2. `BDN.Generated` is your benchmark. By default, BenchmarkDotNet generated an additional project, compile it and run. The measurements logic is in this process; the main application is only a host which collect these measurements.
Any heavy process which consumes the computer resources could affect the performance of your application. Visual Studio is one of such heavy processes. It's ok to perform some dry runs from VS (without attached debugger), but it's recommended to run final benchmarks in a clean environment without any heavy processes (like VS).

**Comment by Mike-EEE** [comment]
Ah!  So weird, I searched in Gitter for "BenchmarkDotNet" and that old room is the one that returned.  I just did another search and now 3 show up.  And it turns out that I actually posted in that one! OMG not doing so good here haha.

As for the processes, after further review what I was experiencing is not specific to VS.  When I do performance testing I close down every app possible (as suggested).  VS is the *only* application that is open.  However, if I do open another application (such as SourceTree), I notice that they too get a little chirpy whenever I run `BDN.Generated`.  So it must be a OS-level communication that is going on (probably to orchestrate thread priority as BDN does rocket off quite mightily as it should. :) ).

OK I think I am squared away for now.  I will ask any sort of questions like these in Gitter from now on.  Thanks you for taking the time to reply, @AndreyAkinshin!
