### ISSUE TITLE
BenchmarkDotNet Competibility with Asp.net web Applications 

### ISSUE THREAD

**Issue by farooqspecials** [dotnet/BenchmarkDotNet#378]
This library is not compatible with ASP.net web Applications in order to benchmark C# code.
If anyone know the method to benchmark C# code in Asp.net web application. please share

**Comment by adamsitnik** [comment]
Hi @farooqspecials You need to add a console app to your solution and then add reference to the asp.net project to it.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, as I understand from the gitter discussion with @farooqspecials, he wants to run benchmarks directly from an ASP.NET app (for some reason). I think it could be useful (e.g. for internal diagnostics on remote servers with will be triggered by a HTTP request), so it makes sense to support it. I tried to run some benchmarks without any lucks because BDN tries to create `BenchmarkDotNet.Artifacts` directly in the IIS folder (and we don't have access to this folder). So, I created this issue: https://github.com/dotnet/BenchmarkDotNet/issues/377 It's not our first problem with directories, so I think that it makes sense to add an API to customize BenchmarkDotNet working directory and put all the generated files in this directory. By default, it should be the binary folder (if we don't have access, we can automatically switch it to something like `%TEMP%/BenchmarkDotNet/`).

**Comment by adamsitnik** [comment]
@AndreyAkinshin  Now I get it, thanks for the explanation!

> By default, it should be the binary folder (if we don't have access, we can automatically switch it to something like %TEMP%/BenchmarkDotNet/).

It would work for our .NET Core Csproj toolchain only. Currently the classic would fail due to lack of dependent dll files in the output folder. If I find a nice solution to this problem we can also solve the shadow copy issue.

**Comment by AndreyAkinshin** [comment]
@adamsitnik is it still an issue?

**Comment by adamsitnik** [comment]
@AndreyAkinshin we still put our dlls in the same folder where the dll which defines benchmark are. This is because they can have some native dependencies, which we can not recognize. So if we put them in the same folder, they are loaded correctly. If we put them to some custom folder, we need to copy all of them. To me it looks like it's not worth the effort. At least I prefer to invest my time doing some other, more performance-related things for BDN.

**Comment by asgerhallas** [comment]
I'm new to BDN, so I'm not sure this is the right issue to address my needs. Please let me know, if I should create another issue - or if it's just not the right library :) 

I have an issue where code seems to run significantly faster on IIS Express than in a console app, which I measured without BDN, but I would now like to go a little deeper. What would I need to run performance benchmarks against a ASP.NET application - running on IIS Express? Can it be done?

**Comment by adamsitnik** [comment]
No progress since 2017, I am closing the issue
