### ISSUE TITLE
Troubles with ClrJob in .NET Core applications

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#393]
Here are my results for `Algo_Md5VsSha256` (the latest changeset in the master branch):
```
 Method |  Job | Runtime |       Mean |    StdDev | Scaled | Scaled-StdDev |
------- |----- |-------- |----------- |---------- |------- |-------------- |
    Md5 |  Clr |     Clr |         NA |        NA |      ? |             ? |
 Sha256 |  Clr |     Clr |         NA |        NA |      ? |             ? |
    Md5 | Core |    Core | 24.3281 us | 0.1419 us |   1.00 |          0.00 |
 Sha256 | Core |    Core | 57.0245 us | 0.5211 us |   2.34 |          0.02 |
    Md5 | Mono |    Mono |         NA |        NA |      ? |             ? |
 Sha256 | Mono |    Mono |         NA |        NA |      ? |             ? |
```
Logs:
```
// Benchmark: Algo_Md5VsSha256.Sha256: Clr(Runtime=Clr)
// *** Generate *** 
// Result = Success
// BinariesDirectoryPath = W:\Work\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\bin\Release\netcoreapp1.1\BDN.Generated\bin\Release\net46

// *** Build ***
// dotnet restore took 1.66s
// dotnet build took 3.02s
// Result = Success

// *** Execute ***
// Launch: 1 / 1
Executable W:\Work\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\bin\Release\netcoreapp1.1\BDN.Generated\bin\Release\net46\BDN.Generated.exe not found
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!
```
Also `MultipleRuntimesTest.SingleBenchmarkCanBeExecutedForMultpleRuntimes` is failed for .NET Core profile (use `runCoreTests.cmd`).

@adamsitnik, could you take a look?

**Comment by adamsitnik** [comment]
@AndreyAkinshin sure, sorry for the trouble. Could you just tell me which version of VS 2017 are you using? There was one update after RTM, I know it changed few things

**Comment by AndreyAkinshin** [comment]
Microsoft Visual Studio Community 2017
Version 15.0.26228.4 D15RTWSVC

**Comment by adamsitnik** [comment]
Fixed. The explanation:

Previous versions of VS required us to set up the `<RuntimeIdentifier>` property in csproj for classic .NET projects. Now VS does not demand it, but we were still setting it and instead of putting the exe to `bin\Release\net46` it was putting it to `bin\Release\net46\$RuntimeIdentifier`

**Comment by EvgeniiDev** [comment]
@adamsitnik 
Hello!
I use RuntimeIdentifier to build x86 applications on x64 sdk, for this I add new MsBuildArgument("/p:RuntimeIdentifier=win-x86").
and the binaries are located in bin\Release\netcoreapp3.1\win-x86
but dotnetbenchmark
looks in bin\Release\netcoreapp3.1
and is falling apart because of this, is it possible to correct this behavior?

**Comment by timcassell** [comment]
@EvgeniiDev Can you please try with the latest [nightly build](https://benchmarkdotnet.org/articles/guides/nuget.html#nightly)?

**Comment by EvgeniiDev** [comment]
@timcassell 
Thanks, now it finds the file, but crashes on startup
// Benchmark Process 32136 has exited with code -2147450750.

**Comment by timcassell** [comment]
I think you need to use 32-bit sdk to build 32-bit runtime. Try passing `--cli <path-to-32-bit-sdk>` argument.
