### ISSUE TITLE
Exception: MSBUILD : error MSB1003: Specify a project or solution file

### ISSUE THREAD

**Issue by gbolahanonamusi** [dotnet/BenchmarkDotNet#399]
Here is my result for a test console application in netcoreapp1.1

```
*** Build ***
dotnet restore took 0.34s
Result = Failure
 Exception: MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```
```

Method |  Job | Runtime | Mean | Scaled | Scaled-StdDev |
------- |----- |-------- |----- |------- |-------------- |
    Bb1 |  Clr |     Clr |   NA |      ? |             ? |
    Bb2 |  Clr |     Clr |   NA |      ? |             ? |
    Bb1 | Core |    Core |   NA |      ? |             ? |
    Bb2 | Core |    Core |   NA |      ? |             ? |
    Bb1 | Mono |    Mono |   NA |      ? |             ? |
    Bb2 | Mono |    Mono |   NA |      ? |             ? |
```

**Comment by AndreyAkinshin** [comment]
@gbolahanonamusi, thanks for the bug report. Could you provide a repro project? Which version of BenchmarkDotNet do you use?

**Comment by adamsitnik** [comment]
Hi @gbolahanonamusi 

We need your .csproj and Visual Studio verson

**Comment by gbolahanonamusi** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <RuntimeIdentifier Condition=" '$(TargetFramework)' == 'net45' ">win7-x86</RuntimeIdentifier>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.10.3" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.1" />
  </ItemGroup>

</Project>
```

**Comment by adamsitnik** [comment]
Ok, so the first problem is that you want to test it for .NET Core, Classic and Mono, but your .csproj contains only netcoreapp1.1 in target framework.

Please change it to:
`<TargetFrameworks>netcoreapp1.1;net45</TargetFrameworks>` and let me know the output

**Comment by AndreyAkinshin** [comment]
> you want to test it for .NET Core, Classic and Mono, but your .csproj contains only netcoreapp1.1 in target framework.

@adamsitnik, could you automatically detect such situation and print a warning with useful instructions?

**Comment by gbolahanonamusi** [comment]
On net45 im getting this error

```
// Benchmark Process Environment Information:
// Runtime=Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1586.0
// GC=Concurrent Workstation
// Job: Clr(Runtime=Clr)

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)
   at BenchmarkTests.BbTest.<Bb1>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BenchmarkDotNet.Running.TaskMethodInvoker`1.ExecuteBlocking(Func`1 future)
   at BenchmarkDotNet.Autogenerated.Runnable.MainMultiAction(Int64 invokeCount)
   at BenchmarkDotNet.Engines.Engine.Jitting()
   at BenchmarkDotNet.Autogenerated.Runnable.Run(Boolean isDiagnoserAttached)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args)
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

// *** Build ***
// dotnet restore took 0.22s
// Result = Failure
// Exception: MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

But same error on netcoreapp1.1

**Comment by peter-takacs** [comment]
Hi,

I recently encountered a similar issue using .NET Core 2 preview, Visual Studio 2017 15.3 preview 6 and BenchmarkDotNet 0.10.9.

I managed to track it down to the fact that during a previous run of BDN that was aborted, no cleanup was performed, so `project.json` files generated by BDN remained within the directory tree of the solution.
This made BDN think that I am using `.json` files for my projects, whereas I am using `.csproj`. 

I looked at the source and saw how BDN determines whether we're using `.json` or `.csproj` and I think it's extremely brittle, since it relies on `preview` being present in the name of the runtime and recursively (!) scans the directory structure for `project.json` files.

I think that this solution is less than ideal, it took me quite a while to figure out what was going wrong. I propose two things to make it easier for people in the future:
  * During build indicate what the automatically detected toolchain was, optionally how BDN reached that conclusion.
  * Make the choice of toolchain something that needs to be explicitly configured while setting up the benchmark. I understand the need for easy setup and sane defaults in configuration, but I believe that is only a feasible route when we can determine the runtime with certainty.

Thoughts?

**Comment by adamsitnik** [comment]
@peter-takacs wow, thanks for tracking this down!

I think that we can just remove the `project.json` support. I will ask on Twitter if anybody is still using it.

**Comment by adamsitnik** [comment]
@peter-takacs I created #526 for it and already removed the project.json support. Thanks for help!

**Comment by dahvid** [comment]
I'm still using it!  The dotnet migrate, just erases all my project.json files (with backups) and then writes blank .csproject files.  If you do get rid of them, I still need a way to build my app from a command line.  It's part of a Docker build process.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, since we are not supporting project.json anymore, could we close this issue as won't fix?

**Comment by adamsitnik** [comment]
@AndreyAkinshin good idea

**Comment by marubadi** [comment]
Can anyone help me with project.json

**Comment by AndreyAkinshin** [comment]
@marubadi, we don't support `project.json`-based projects in the latest BenchmarkDotNet versions because it's a legacy format.

**Comment by adamsitnik** [comment]
@marubadi you need to downgrade to `0.10.9` to have `project.json`. Unfortunaly if there are any bugs we are not going to solve them because we don't support it anymore.

If you are very desperate to have it you need to download the [code](https://github.com/dotnet/BenchmarkDotNet/commit/93dc6e638aab62dddd6bba50aa13b04645663cfd) that I have removed and copy it to your own repository and get it working,
