### ISSUE TITLE
Doesn't work for core cspoj (the same works for classic)

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/BenchmarkDotNet#427]
0.10.3 on VS 2017,  core 1.1  

Expected result: on core should work like in classic
Actual result: empty report full of N/A. Exception if RankColumn included. 

Files: VS project.
[Benchmark.zip](https://github.com/dotnet/BenchmarkDotNet/files/945356/Benchmark.zip)

If core support is expremental please state it clear. I can stay with classic.

**Comment by adamsitnik** [comment]
Your log states clear what is wrong ;)

Your csproj supports only .NET Core 1.1, but you are using `[ClrJob]` attribute which enforces the classic .NET 4.6 build.
Instead of `[ClrJob]//, CoreJob]` you should use `[CoreJob]` or just remove it and the default value will be used.
If you want to use both `[ClrJob, CoreJob]` your `.csproj` needs to have `<TargetFrameworks>netcoreapp1.1;net46</TargetFrameworks>`.

**Comment by rpokrovskij** [comment]
Got it. Thank you.
