### ISSUE TITLE
[Minor feature request] Please make GcStats.AllocationQuantum public

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#450]
Subj:)
As an option, what about exposing it as a member of `BenchmarkEnvironmentInfo` ?

**Comment by adamsitnik** [comment]
> Please make GcStats.AllocationQuantum public

@ig-sinicyn maybe you could create PR when you want us to expose something? It would most probably take less time than creating the issue and us to respond ;)

> As an option, what about exposing it as a member of BenchmarkEnvironmentInfo ?

only exposing or also printing in the summary?

**Comment by ig-sinicyn** [comment]
> @ig-sinicyn maybe you could create PR when you want us to expose something? 

:)
Ok, will do in a day or two.

> only exposing or also printing in the summary?
Only exposing, I do not think this is important enough.

**Comment by adamsitnik** [comment]
> Ok, will do in a day or two.

Great! Please don't hesitate, you have a lot of great ideas!

> Only exposing, I do not think this is important enough.

From the domain perspective I think it belongs to GcStats, but I can also see the need for `BenchmarkEnvironmentInfo` because it can be different for some runtimes. Maybe keep it in GcStats and add extra property to `BenchmarkEnvironmentInfo` that will return this value?

**Comment by ig-sinicyn** [comment]
>Great! Please don't hesitate, you have a lot of great ideas!



I wish I had time to complete at least one:)

>Maybe keep it in GcStats and add extra property to `BenchmarkEnvironmentInfo` that will return this value?

+1 here :)
Will add in PR.
