### ISSUE TITLE
MemoryDiagnoser and JsonExporter

### ISSUE THREAD

**Issue by ipjohnson** [dotnet/BenchmarkDotNet#453]
I'm trying to get memory diagnostic results to be exported as part of JsonExporter.* and I can't seem to get it to work. What am I missing? 

```
    public class BenchmarkConfig : ManualConfig
    {
        public BenchmarkConfig()
        {
            Add(Job.Clr, Job.Core);
            Add(new MemoryDiagnoser());
            Add(new CompositeExporter(JsonExporter.Full));
        }
    }
```

**Comment by Teknikaali** [comment]
It seems like the `JsonExporter` doesn't include the `MemoryDiagnoser`'s results yet, so @ipjohnson you weren't missing anything at all, _per se_.

This is a sample output for the `MemoryDiagnoser` in Json, if we simply include the `GcStats` property:
```json
...
"Memory":{
   "Gen0Collections":37628,
   "Gen1Collections":0,
   "Gen2Collections":0,
   "TotalOperations":15728640,
   "BytesAllocatedPerOperation":10048
},
...
```

One con side of adding the `GcStats`-property straight into `JsonExporter`'s output would be that _the operation isn't conditional_:
If there is no `MemoryDiagnoser` attached we will still get that "Memory"-entry in the Brief/Full Json export but with default values (it's a `struct`).

To overcome this con, we could check for the `MemoryDiagnoser` in `JsonExporterBase.ExportToLog`-method like so:

```csharp
// Initialize the normal data for export
var data = new Dictionary<string, object>
{
    { "DisplayInfo", r.Benchmark.DisplayInfo },
    ...
};

// Add the "Memory" entry only if a MemoryDiagnoser has been configured for the benchmark
if(summary.Config.GetDiagnosers().Any(diagnoser => diagnoser is MemoryDiagnoser))
{
    data.Add("Memory", r.GcStats);
}
```

@adamsitnik is this the correct way to perform the check if a `MemoryDiagnoser` is defined for the benchmark? Or is this kind of operation "forbidden" because of specific relationships between modules?

As I don't have any deep knowledge of what kind of relationships exist between exporters and diagnosers, but I could only make a good guess, that _it's the exporter's job to handle different diagnosers' output data inside the `ExporterBase.ExportToLog(...)` method._

`IDiagnoser.DisplayResults(ILogger logger)` method would suggest that the result could be outputted through the diagnoser, but then one would have to handle all the different exporters inside the diagnoser itself, and that in turn would switch the relationship the other way around and handling the output would become much harder.

I can make the PR for this if that `GetDiagnosers()` method usage is ok. I can also include a quick fix for the same thing on the `XmlExporter`, as it's pretty straightforward to make the `Memory` visible there. I'd need some more time to explore the other exporters, but it seems like most of them have already some kind of `MemoryDiagnoser` handling in place after running through the relevant samples.
