### ISSUE TITLE
[Question] Am I experiencing dead code removal?

### ISSUE THREAD

**Issue by qstarin** [dotnet/BenchmarkDotNet#472]
I've been working on micro optimizing modulo for a specific use case and someone suggested that my results don't seem realistic. It hadn't occurred to me but 1 nanosecond per operation would be 4 CPU cycles at 4.0GHz. I'm getting 1 ns/op for a method that would be a number of cpu operations.

Have I done something wrong that's causing the JIT to not actually call something, making the operation time unrealistically small, or am I misinterpreting the meaning of the results?

    BenchmarkDotNet=v0.10.8, OS=Windows 10 Redstone 1 (10.0.14393)
    Processor=Intel Core i7-6700K CPU 4.00GHz (Skylake), ProcessorCount=8
    Frequency=3914062 Hz, Resolution=255.4891 ns, Timer=TSC
    dotnet cli version=1.0.4
      [Host]     : .NET Core 4.6.25211.01, 64bit RyuJIT
      DefaultJob : .NET Core 4.6.25211.01, 64bit RyuJIT

       Method |     Mean |     Error |    StdDev |
    --------- |---------:|----------:|----------:|
           HC | 5.622 ns | 0.0357 ns | 0.0334 ns |
     Mersenne | 1.050 ns | 0.0108 ns | 0.0101 ns |

Benchmarks:

    public class ModuloHC
    {
        private readonly ulong _dividend;
        
        public ModuloHC()
        {
            // don't use a constant value as the compiler might optimize the whole thing away
            _dividend = (ulong)new Random().Next();
        }

        [Benchmark]
        public ulong HC() => _dividend % 5;

        [Benchmark]
        public ulong Mersenne()
        {
            ulong dividend = (_dividend >> 32) + (_dividend & 0xFFFFFFFF);
            dividend = (dividend >> 16) + (dividend & 0xFFFF);
            dividend = (dividend >> 8) + (dividend & 0xFF);
            dividend = (dividend >> 4) + (dividend & 0xF);
            dividend = (dividend >> 4) + (dividend & 0xF);
            if (dividend > 14) dividend = dividend - 15;
            if (dividend > 9) dividend = dividend - 10;
            if (dividend > 4) dividend = dividend - 5;
            return dividend;
        }
    }

If I add some more tests, the results are even more suspect, with some completing in seemingly no time at all (would the JIT re-use a result since _dividend doesn't change? except if it did why would `_dividend % 5` not get the same optimization).

```
// * Summary *

BenchmarkDotNet=v0.10.8, OS=Windows 10 Redstone 1 (10.0.14393)
Processor=Intel Core i7-6700K CPU 4.00GHz (Skylake), ProcessorCount=8
Frequency=3914062 Hz, Resolution=255.4891 ns, Timer=TSC
dotnet cli version=1.0.4
  [Host]     : .NET Core 4.6.25211.01, 64bit RyuJIT
  DefaultJob : .NET Core 4.6.25211.01, 64bit RyuJIT


                    Method |      Mean |     Error |    StdDev |    Median |
-------------------------- |----------:|----------:|----------:|----------:|
                 Modulo_HC | 5.2146 ns | 0.1252 ns | 0.1171 ns | 5.1694 ns |
            Modulo_Func_HC | 5.0715 ns | 0.0304 ns | 0.0285 ns | 5.0669 ns |
            Local_Mersenne | 1.0433 ns | 0.0512 ns | 0.0750 ns | 1.0041 ns |
                  Mersenne | 1.0048 ns | 0.0180 ns | 0.0150 ns | 1.0006 ns |
      Pow2_Local_Modulo_HC | 0.0000 ns | 0.0000 ns | 0.0000 ns | 0.0000 ns |
 Pow2_Local_Func_Modulo_HC | 0.0220 ns | 0.0219 ns | 0.0194 ns | 0.0172 ns |
    Pow2_Local_Func_Modulo | 5.0333 ns | 0.0113 ns | 0.0100 ns | 5.0282 ns |
            Pow2_Modulo_HC | 0.0188 ns | 0.0261 ns | 0.0231 ns | 0.0037 ns |
               Pow2_Modulo | 5.0288 ns | 0.0033 ns | 0.0026 ns | 5.0282 ns |
         Pow2_Local_And_HC | 0.0265 ns | 0.0396 ns | 0.0370 ns | 0.0041 ns |
    Pow2_Local_Func_And_HC | 0.0098 ns | 0.0011 ns | 0.0009 ns | 0.0097 ns |
       Pow2_Local_Func_And | 0.0080 ns | 0.0137 ns | 0.0128 ns | 0.0008 ns |
               Pow2_And_HC | 0.0409 ns | 0.0307 ns | 0.0341 ns | 0.0326 ns |
                  Pow2_And | 0.0003 ns | 0.0008 ns | 0.0007 ns | 0.0000 ns |

```
Extended benchmarks:

    public class ModuloHC
    {
        private readonly ulong _divisor16;
        private readonly ulong _dividend;
        
        public ModuloHC()
        {
            // don't use constant values as the compiler might optimize the whole thing away
            var counter = new List<string>();
            counter.Add("");
            _divisor16 = (ulong)counter.Count() + 15;
            _dividend = (ulong)new Random().Next();
        }

        [Benchmark]
        public ulong Modulo_HC() => _dividend % 5;

        [Benchmark]
        public ulong Modulo_Func_HC() => ModuloOperator(_dividend, 5);

        [Benchmark]
        public ulong Local_Mersenne()
        {
            ulong dividend = (_dividend >> 32) + (_dividend & 0xFFFFFFFF);
            dividend = (dividend >> 16) + (dividend & 0xFFFF);
            dividend = (dividend >> 8) + (dividend & 0xFF);
            dividend = (dividend >> 4) + (dividend & 0xF);
            dividend = (dividend >> 4) + (dividend & 0xF);
            if (dividend > 14) dividend = dividend - 15;
            if (dividend > 9) dividend = dividend - 10;
            if (dividend > 4) dividend = dividend - 5;
            return dividend;
        }

        [Benchmark]
        public ulong Mersenne() => Modulo.Implementations.Long.Mersenne5(_dividend);

        // Modulo.Implementations.Long has the same implementations as found here 
        // just in another assembly (and with MethodImplOptions.AggressiveInlining)

        [Benchmark]
        public ulong Pow2_Local_Modulo_HC() => _dividend % 16;

        [Benchmark]
        public ulong Pow2_Local_Func_Modulo_HC() => ModuloOperator(_dividend, 16);

        [Benchmark]
        public ulong Pow2_Local_Func_Modulo() => ModuloOperator(_dividend, _divisor16);

        [Benchmark]
        public ulong Pow2_Modulo_HC() => Modulo.Implementations.Long.ModuloOperator(_dividend, 16);

        [Benchmark]
        public ulong Pow2_Modulo() => Modulo.Implementations.Long.ModuloOperator(_dividend, _divisor16);

        [Benchmark]
        public ulong Pow2_Local_And_HC() => _dividend & 15;

        [Benchmark]
        public ulong Pow2_Local_Func_And_HC() => ShiftAnd(_dividend, 16);

        [Benchmark]
        public ulong Pow2_Local_Func_And() => ShiftAnd(_dividend, _divisor16);

        [Benchmark]
        public ulong Pow2_And_HC() => Modulo.Implementations.Long.ShiftAnd(_dividend, 16);

        [Benchmark]
        public ulong Pow2_And() => Modulo.Implementations.Long.ShiftAnd(_dividend, _divisor16);

        static public ulong ModuloOperator(ulong dividend, ulong divisor) => (dividend % divisor);

        static public ulong ShiftAnd(ulong dividend, ulong divisor) => (dividend & (divisor - 1));
    }

**Comment by AndreyAkinshin** [comment]
Hey, @qstarin.

Everything sounds pretty realistic to me. Some thoughts:

1. If you are not sure about which optimization JIT-compiler does, the best way is checking the assembly code (instead of blind guessing). If you are going to do such kind of optimization, working with the assembly should be one of the basic skills.
2. What exactly do you want to measure: latency or throughput? (e.g. [here](http://aakinshin.net/blog/post/perfex-div/) I measure latency) How are you going to use results? Usually, the main performance impact in such cases is on the calling code level: do we have a memory bottleneck, what's going on with the instruction level parallelism, and so on. In your case, you are trying to measure a very strange metric, and I have no idea how it can affect the real code.
3. Are you going to work with the *the same number* each time in real code? If you are going to work with different numbers, the main problem in the `Mersenne` method will be branch mispredicts. Right now you have a perfect situation for the branch predictor, because of that, `Mersenne` works so fast. Also, please, never use `Random` without seed in benchmarks: you will get new execution path each time.
4. By default, BenchmarkDotNet thinks that the performance of the `ulong Foo() => 0;` method is `0ns`, it's your baseline. If you have a method which works as fast as `Foo`, you will get `0ns` (or something like `0.0003ns` because of the noise).

The division is one of the most tricky CPU instructions. Especially if are want to check algorithms which involve branch prediction. It's really hard to design a set of *microbenchmarks* which cover the whole performance space and get some "general case" results; it requires hours (or days) of work.

A recommendation: if you want to optimize a specific use case, you should benchmark this specific use case instead of trying to benchmark too synthetic cases (which probably will not be relevant to your problem).

**Comment by qstarin** [comment]
Thank you for the response. Honestly, this is as much an exercise in improving my benchmarking skills and learning to utilize BenchmarkDotNet properly. It is a real application, but the optimization was inspired more by can I rather than I really need to.

1. Yes, I need to familiarize myself with the tools for inspecting assembly outputted by the JIT (and probably brush up on my x86 assembly)

2. I believe what I want to measure is latency. I see your example and that helps me understand how instruction level parallelism might affect the results and how to change the benchmark to avoid that.

It sounds like I may get more realistic results, or at least another viewpoint that is valuable, by benchmarking at a higher level - actually retrieving the objects from the pool, for example.

3. I will not be working with the same number. The specific use case is an object pool that must hand out instances evenly to multiple consuming threads. Modulo is used to calculate the index into an array from a counter that is incremented with Interlock on each access. The size of the array is determined at runtime, and the array can be rebuilt with a different size during execution (very infrequently compared to the number of accesses).

Good point about Random.Next, I had only put that in the sample here to simplify but I see the general principle you're pointing out.

It sounds like I would want a single benchmark to perform the calculation on a number of dividends, to avoid the unrealistically good branch prediction from using a single dividend. Something like:

    public class ModuloMod
    {
        public ulong rl;
        private ulong _lDiv5;
        private ulong _lDiv16;

        public ModuloMod()
        {
            // real use case won't have constant divisors, avoid the compiler getting tricky
            var counter = new List<string> { "", "", "", ""};
            _lDiv5 = (ulong)counter.Count() + 1;
            _lDiv16 = (ulong)counter.Count() + 12;
        }


        [Benchmark] public ulong Long_Mod() => LongHarness(n => Modulo.Implementations.Long.ModuloOperator(n, _lDiv5));
        [Benchmark] public ulong Long_Mersenne() => LongHarness(Modulo.Implementations.Long.Mersenne5);
        [Benchmark] public ulong Long_Pow2() => LongHarness(n => Modulo.Implementations.Long.ShiftAnd(n, _lDiv16));

        private ulong LongHarness(Func<ulong, ulong> mod)
        {
            for (ulong i = 0; i < 512; i++)
                rl += mod(i);
            return rl;
        }
    }

4. Am I understanding you correctly that BenchmarkDotNet actually measures `ulong Foo() => 0;` during a run and then adjusts all other results by subtracting the time it takes to run `ulong Foo() => 0;`? Meaning, if `ulong Foo() => 0;` takes 1ns to run in my environment and my benchmarked implementation takes 3ns to run in my environment I will see 2ns/op as my result?

Thank you again for your reply, that helped considerably.

**Comment by tannergooding** [comment]
@qstarin, as a reference. A similar issue was hit with the `System.Numerics.Vector` perf tests. The original issue was discovered in an initial pull request here: https://github.com/dotnet/corefx/pull/16453.

They were later fixed up here: https://github.com/dotnet/corefx/pull/16847

At the time, we determined the "best" approach was to have two versions of the function:
* A "normal" benchmark that doesn't modify the input and consumes the output (but does not aggregate the outputs, thus only the last output is actually used).
* A "canary" benchmark, which modifies the input and aggregates the output values together

The "normal" benchmark helps ensure we get accurate results that aren't bloated by noise or additional operations that may take longer than the operation we are benching. However, this has the downside that certain JIT optimizations could "break" the benchmark in the future (due to constant folding, dead code optimization, etc).

The "canary" benchmark helps ensure we get benchmark results that fully test the code we are interested in (the JIT should never optimize the calls away, etc). It also helps get numbers for how the code may be used in a real application (rather than just attempting for raw throughput).

**Comment by AndreyAkinshin** [comment]
@qstarin,
> Am I understanding you correctly that BenchmarkDotNet actually measures ulong Foo() => 0; during a run and then adjusts all other results by subtracting the time it takes to run ulong Foo() => 0;? Meaning, if ulong Foo() => 0; takes 1ns to run in my environment and my benchmarked implementation takes 3ns to run in my environment I will see 2ns/op as my result?

Yes, you are correct, we call it "Idle" iterations: we measure an empty method with the same signature, see also: http://benchmarkdotnet.org/Internals/HowItWorks.htm

Do you have any additional questions related to BenchmarkDotNet?

**Comment by qstarin** [comment]
Awesome. Thank you so much for taking the time to reply, and of course for your work on this excellent library. I have no more questions and will close the issue here.
