### ISSUE TITLE
Iteration cleanup runs before the benchmark

### ISSUE THREAD

**Issue by kayanme** [dotnet/BenchmarkDotNet#481]
Example:
```
  class Program
    {

        static void Main(string[] args)
        {      
            BenchmarkDotNet.Running.BenchmarkRunner.Run<BadBench>();
            Console.ReadLine();
        }
    }

   

    
    public class BadBench
    {
        [Benchmark]
        public void Test()
        {
            Console.WriteLine("Test");
            Thread.Sleep(1000);
        }


        [IterationSetup]
        public void Init()
        {
            Console.WriteLine("Init");
        }

        [IterationCleanup]
        public void Clean()
        {
            Console.WriteLine("Clean");
        }
    }
```
I'm expecting  to have "Test" before "Clean", am I? Or do I misunderstand something? Right now it goes right after "Init"
Version 0.10.8

**Comment by ig-sinicyn** [comment]
It's #464 :)

**Comment by kayanme** [comment]
I saw that bug, but didn't see the same problem. Evenmore, @adamsitnik told about his use case, which, surpisingly, seems working with the correct order. I wonder why.

**Comment by smitpatel** [comment]
https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Templates/BenchmarkProgram.txt#L120
Here is the issue. `IterationCleanup` is being called before `Jitting()` Perhaps it does not occur for Monitoring due to `Jitting()` not being called. I believe the IterationCleanup should be called after `Jitting()`


For me the use case is like this,
I am creating an object during `IterationSetup` & disposing it during `IterationCleanup`. Creating new instance is costly operation so I don't want that in my benchmark method. But due to nature of the benchmark, I need new instance everytime.

**Comment by smitpatel** [comment]
@adamsitnik - Thanks for quick response. Is there an estimate when 0.10.9 will make it to NuGet?

**Comment by AndreyAkinshin** [comment]
@smitpatel, I want to release next version on this week.

**Comment by adamsitnik** [comment]
@smitpatel you get can it today from our CI feed:

```xml
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```
