### ISSUE TITLE
[Proposal][Enhancement] Integrate SonarQube for continuous code quality.

### ISSUE THREAD

**Issue by Ky7m** [dotnet/BenchmarkDotNet#522]
What do you think about integration with [SonarQube](https://www.sonarqube.org/)?
**BenchmarkDotNet** is a very mature project and code quality is on excellent level as well but I think that would be good to have tool that tracks a monitors code quality on regular basis. 
As start point it can be SonarQube with customized ruleset.
Example of dashboard and code analysis https://sonarcloud.io/dashboard?id=BenchmarkDotNet

Would be great to hear your feedback on this.

P.S. I can take care of integration process if it is relevant. :)

**Comment by AndreyAkinshin** [comment]
@Ky7m, thanks for the kind words about our code quality. Unfortunately, we have a lot of bad code because of some legacy reasons. I want to clean up it, but we have some unmerged branches now, and @adamsitnik and I should make some decision about it before the clean up (otherwise it will be impossible to merge).

Next, to be honest, the SonarQube report looks strange to me. Most of the errors in the report are about the Samples project which contains such code by design (I want to do some work here as well, but it's a different topic). The main project in the solution is `BenchmarkDotNet.Core`, but I don't see it in the report. I work on BenchmarkDotNet in Rider (or VS+R# in some cases), and it shows me about 700 issues (hints, suggestions, warning). I'm going to fix them all one day (and keep the source code "clean" after that), but I guess that code smells is a typical situation for any mature projects with a lot of legacy code. =)

Thus, I don't think that it makes sense to integrate BenchmarkDotNet with SonarQube *right now*. But we can try it again after my huge cleaning and check how it will go.

**Comment by Ky7m** [comment]
@AndreyAkinshin, thank you for your response and entire picture. In this case, it makes a perfect sense and SonarQube is not the best candidate. 
Instead of SonarQube, it is possible to integrate [JetBrains.ReSharper.CommandLineTools](https://www.nuget.org/packages/JetBrains.ReSharper.CommandLineTools) or any other tool, just let me know.
I think that we can close this particular issue.

**Comment by AndreyAkinshin** [comment]
Yeah, CommandLineTools looks like a good option. But it will be useless without the huge clean up. So, I will create another issue as soon as I get the clean code base.

**Comment by Ky7m** [comment]
Just to leave a note about additional option of code analysis https://codescene.io/projects/176/jobs/3969/results
