### ISSUE TITLE
Add support for stats on benchmark return result

### ISSUE THREAD

**Issue by jschneidereit** [dotnet/BenchmarkDotNet#523]
I believe it would be useful to have the same statistical analysis that is performed on benchmark timing on a numeric return type of a benchmark method `float`, `double`, `int`, etc.

Certain implementations of certain algorithms can be more or less accurate based on the parameters and therefore the return result of my benchmark is important data. 
E.g.: Let's say I have an algorithm to find the area under a curve, and am splitting that curve into sections and using a thread per segment. I'd like to scale up threads and see the performance benefits (easily done with `[Params(1, 2, 4, 8)]` and compare the precision that I gain by increasing the number of thread jobs (decreasing the size of the segment) which as far as I can tell is not easily done using BenchmarkDotNet. 

Apologies if this already exists I was unable to find something like this after digging through the docs, I figured a custom column would do the trick but it appears that the data there is loaded at some time not during the benchmark process. If it doesn't exist and someone can point me in the right direction I'd be happy to implement!

**Comment by AndreyAkinshin** [comment]
Hey @jschneidereit,

We don't support such feature by design: BenchmarkDotNet supposes that the return value can be used only for preventing dead code elimination. Everyone who ask about an additional column for benchmark result has own needs, and it's really hard to implement a general approach which will make everyone happy and doesn't introduce additional troubles for common benchmarking scenarious.

So, you should implement own custom column and decide how to collect data and how to display it.
