### ISSUE TITLE
Confusing Doc links

### ISSUE THREAD

**Issue by Zoxive** [dotnet/BenchmarkDotNet#596]
If anyone attempts to read the docs here on github via https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/guide/Overview.md

All links 404 becase they are going to .htm instead of .md

Was about to create a PR fixing all the doc links to use .md instead of .htm then realized its because they are .htm for http://benchmarkdotnet.org

**Comment by adamsitnik** [comment]
Hi @Zoxive 

I understand your point of view, but I am afraid that there is nothing that we can do to prevent our users to search the docs folder instead of going to our docs page.

Link to docs is the first link on our repository's page

![image](https://user-images.githubusercontent.com/6011991/33378196-59ad7c36-d514-11e7-8e39-456f24975389.png)

It's also first link on our useful links list

![image](https://user-images.githubusercontent.com/6011991/33378254-84a789fe-d514-11e7-8b1a-49af5ee249ea.png)

If you have any idea please feel free to reopen the issue.
