### ISSUE TITLE
Proper HTML escaping of BenchmarkAttribute Description 

### ISSUE THREAD

**Issue by ENikS** [dotnet/BenchmarkDotNet#599]
I have descriptions containing symbols ``<>``. Something like this:
```
[Benchmark(Description = "Benchmarking Container.Resolve<SomeType>()")]
```
When displayed in console the descriptions are correct but generated markdown and HTML are invalid. Anything that is included in these brackets is ignored ending up with something like this: ``Container.Resolve()``.

 Could you please add extra step to properly escape markdown and HTML?

**Comment by AndreyAkinshin** [comment]
@ENikS, it's a good idea, thanks.

**Comment by Chrisgozd** [comment]
I was looking into this.

The line that needs to be changed is here: 
https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Exporters/HtmlExporter.cs#L73

The change is to escape the html, because the text <sometype> gets rendered as an html entity and not text, so we need to replace it with the respective &#60; and &#62;

Since we pass a string[] and not a string to Table.PrintLine, we either need to
a) edit the text before we send it (because other exporters share Table.PrintLine) and we only want to escape for HtmlExporter.
b) send some sort of parameter to tell Table.Printline that html is being printed.

**Comment by adamsitnik** [comment]
@Chrisgozd the other solution would be to inline `Table.Printline` for Html Exporter. `Table.Printline` performs pad left, which is nor required for HTML.

**Comment by Chrisgozd** [comment]
That works for me.

Any qualms with bringing in System.Web to the project? I'd like to use HttpUtility.EncodeHtml to encode the html.

**Comment by adamsitnik** [comment]
> Any qualms with bringing in System.Web to the project? I'd like to use HttpUtility.EncodeHtml to encode the html.

We try to keep the number of the dependencies as low as possible. We support .NET, Mono, Core and soon are going to support CoreRT and sometimes even small dependency breaks something in one of the scenarios. If it is possible please implement/copy EncodeHtml

**Comment by AndreyAkinshin** [comment]
Agree with @adamsitnik.
Moreover, `HttpUtility.EncodeHtml` requires .NET Core 2.0/.NET Standard 2.0, it will not work on .NET Core 1.1
See https://docs.microsoft.com/en-us/dotnet/api/system.web.httputility?view=netcore-2.0

**Comment by ENikS** [comment]
Will it apply to generated markdown as well?

**Comment by AndreyAkinshin** [comment]
@ENikS, no, @Chrisgozd implemented a fix specifically for html. Feel free to open another issue if you need escaping for markdown.

**Comment by ENikS** [comment]
@AndreyAkinshin Markdown WAS my target, I added HTML as afterthought.
I am publishing results on GitHub and using markdown for that.

**Comment by AndreyAkinshin** [comment]
@ENikS, sorry, I misread your original message, my bad. Let's continue to discuss it in https://github.com/dotnet/BenchmarkDotNet/issues/608

**Comment by ENikS** [comment]
No biggie
