### ISSUE TITLE
Add ability to specify arguments for a method under benchmark

### ISSUE THREAD

**Issue by alexandrnikitin** [dotnet/BenchmarkDotNet#60]
Something like this:

``` csharp
[Benchmark("3 element benchmark", new[] {1, 2, 3})]
public void Method(int[] arr)
{
    // ...
}
```

**Comment by alexandrnikitin** [comment]
Will it be useful? What do you think?

**Comment by dadhi** [comment]
+1

Just need that recently. Bmarking against a fields is not right, if I need to check an access to parameter.

**Comment by AndreyAkinshin** [comment]
Measurement of overhead will be very hard. In this case, we will also measure the passing of the parameter. Of course, we can generate the `Idle` method with the same signature, but I'm not sure that it is a correct way and we will not have any nasty side-effects from JIT (it is important in the case of nanosecond benchmarks).
However, it is an interesting idea. I should try to implement this feature and investigate accuracy.
@mattwarren, what do you think?

**Comment by mattwarren** [comment]
yeah I agree it sounds like a nice idea. I didn't think about *injecting* parameters when I wrote the current `Params(..)` code.

But I agree with @AndreyAkinshin, we should only do it if we can guarantee accuracy.

One a related note, has any got any idea about the different in speed and assembly instructions when you are accessing a parameter instead of a field? What's the difference in overhead?

**Comment by AndreyAkinshin** [comment]
> What's the difference in overhead?

It is a good question, I will investigate it.

**Comment by omariom** [comment]
Parameters of simple types are very likely to be received in registers. Access to a field requires an indirection via this (RCX reg) at least once.

**Comment by omariom** [comment]
Another example - JIT can eliminate bounds checking when the array comes in parameters.

**Comment by adamsitnik** [comment]
It will be tracked as part of #256
