### ISSUE TITLE
Suggestion: Simple solution for simple tests 

### ISSUE THREAD

**Issue by ricardok1** [dotnet/BenchmarkDotNet#602]
Hi there
Thanks for your great job on this. 
Following our exchanged twitter let me explain my suggestion.

As a "casual user" of this kind of performance analysers, I see one big gap to use it more often.
The structure to initialize the test doesn't allow to spread and test inside a big application without creating a special project.

My suggestion is to be able to make something like this inside my program:
```
var summary = BenchmarkRunner.Init(
             string BigOldMethod            (or a better suitable type)
             string Alt_MethodToTest_1
             string Alt_MethodToTest_2
             \\ optional string TestName
             \\ optional BenchmarkRunnerOptions   (required or optional)
         ); 
(...)
var i = BigOldMethod();
var x = Alt_MethodToTest_1();
var z = Alt_MethodToTest_2();

Assert.AreEqual( i, x);
Assert.AreEqual( i, z);
(...)
summary.ProduceOutput("TestName"); 
```
I see making 10x more use of the library if this could be make as this.
Do you think worth the effort?

Thanks
Ricardo (from Portugal)

**Comment by AndreyAkinshin** [comment]
Could you explain your problem in detail? Why do you want pass methods to BenchmarkRunner as strings instead of the default approach?

**Comment by AndreyAkinshin** [comment]
@ricardok1, the source code in your suggestion uses `BenchmarkRunner`, so it has a dependency to `BenchmarkDotNet`. Why do you want to hardcode method names as strings instead of introducing one additional small class which contains all the benchmarks?

**Comment by ricardok1** [comment]
Sorry about making tooooo simple marking methods as strings. The choice is wherever the best (Action, Func, ...) -  I pointed as "or a better suitable type" :-)

My point here is to use your library and test different scenarios without the need to prepare a project for it.

If I want to test something different, I just want to be able to use a snippet with initialisation, point to methods and run. No big deal.

**Comment by adamsitnik** [comment]
Hi @ricardok1 

We generate, build and execute a new project for every benchmark. So we need to have something that we can reference in generated C# files. If we have an `Action` it can be anything (how to create `.cs` file which will reference to this particular method if we don't know what it is?). If we have class and methods we can generate code that is simply calling the benchmarked methods.

We could, of course, use `expressions` and get the corresponding C# for the benchmarked code. The thing is that as of today we don't want to do this because there is simply a lot of other important things that we have to implement. And also our entire codebase relies on having methods and types, not lambdas. So the time investment would be too big for too little gain for us. This is why I am closing this issue.

Thanks for sharing your feedback!
