### ISSUE TITLE
LSD may be skewing the results of nano-second benchmarks

### ISSUE THREAD

**Issue by redknightlois** [dotnet/BenchmarkDotNet#611]
I stumbled upon this a few months ago, but I attribute it to an improvement on the Kaby Lake architecture regarding call infrastructure. Now I am not that sure :D

The story goes like this: A few months ago I noticed that while working on my Skylake based computer at work the usual empty call executed in a loop had a cost while running the very same benchmark on my home computer which is a Kaby-Lake based processor, the cost was waaaaay lower. 

Fast-forward to today, I stumbled upon a quite unknown piece of information. It appears the Skylake processor has a bug in the Loop Stream Detector when running with HyperThreading enabled, so BIOS and Kernel devs have been disabling it for a while [1] . Coffee-Lake is fixed and arguably enough newer revisions of the Kaby-Lake may be too. So even in HT scenarios, it may be enabled. 

That somehow explains the unusual behaviour I had observed between the two. While Skylake runs the loop without the LSD, Kaby-Lake could be running entirely from the LSD skewing the cost lower. On microseconds, the skew is very low but on nano-seconds ones that could become an issue. 

Food for thought.  

[1] https://lists.debian.org/debian-devel/2017/06/msg00308.html

**Comment by AndreyAkinshin** [comment]
@redknightlois, thanks for the report.

I know about the empty call loop phenomena in Skylake. Unfortunately, it's hard to explain it in a few sentences, but I'm going to blog about it in 2018. Anyway, thanks for the note about Kaby Lake and Coffee Lake, I should check it as well.

The main question in the context of BenchmarkDotNet: do you have examples when BenchmarkDotNet shows incorrect results? E.g. non-zero time for something like `[Benchmark]void Foo(){}`?
I already solved this puzzle, and the cure is `UnrollFactor`. Long story short, we generate (by default)
```cs
for (int i = 0; i < N / 16; i++)
{
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
    Foo();
}
```
instead of
```cs
for (int i = 0; i < N; i++)
{
    Foo();
}
```
This simple trick allows getting correct stable results for nanobenchmarks.
Please, let me know if it doesn't work for you.

**Comment by redknightlois** [comment]
@AndreyAkinshin Difficult to tell if they are not correct :D ... but as it was noticeable I prefer to err on the safe side and report the behaviour in case you haven't stumble upon it before. If what I am looking at Kaby-Lake is actually an artifact it appears that the unrolling factor may not be high enough to cover the 64 uops the LSD is capable to work with.

**Comment by thyams** [comment]
Just a caveat, there is an old programming trick to prevent HT logical processor to be used.

Manually create thread, attach the affinity to odd cores/logical processors. Odds are always physical cores.

**Comment by adamsitnik** [comment]
I am closing this issue since we have most probably solved it with the `UnrollFactor` long time ago.
