### ISSUE TITLE
Proper way to run BenchmarkDotNet on macOS/Linux

### ISSUE THREAD

**Issue by TheAngryByrd** [dotnet/BenchmarkDotNet#653]
I'm trying to get run BenchmarksDotNet on macOS/Linux however I'm running into some snags.  Many versions ago I used to be able to run it as mono being the host process and would run mono and core jobs but now I can't seem to do that anymore.

With `mono App.exe` it won't run the CoreJob tests

```
BenchmarkDotNet does not support running .NET Core benchmarks when host process is Mono, benchmark 'SleepMarks.Thread: Job-TPQGUE(Runtime=Core, LaunchCount=1, TargetCount=3, WarmupCount=3) [sleepTime=0]' will not be executed
```

If I run it as `dotnet run -f netcoreapp2.0` it won't run the mono jobs.
```
Classic .NET toolchain is supported only for Windows, benchmark 'SleepMarks.Thread: Job-KUVJKN(Runtime=Mono, LaunchCount=1, TargetCount=3, WarmupCount=3) [sleepTime=0]' will not be executed
```

Is getting both to run in the same benchmark not supported?

**Comment by adamsitnik** [comment]
Hi @TheAngryByrd 

I have faced this problem at work today. I am the person who added this limitation, the problem is that I don't remember why...

Anyway, I have removed it, tested and it works as expected now.

So how to compare Mono vs .NET Core with BenchmarkDotNet now:

1. Define a custom config which has two jobs:

```cs
public class BenchmarkConfig : ManualConfig
{
	public BenchmarkConfig()
	{
		Add(Job.Default.With(Runtime.Core).With(CsProjCoreToolchain.From(NetCoreAppSettings.NetCoreApp20)).AsBaseline().WithId("2.0"));
		Add(Job.Default.With(Runtime.Mono).WithId("Mono"));

		Add(MemoryDiagnoser.Default);

		Add(DefaultConfig.Instance.GetValidators().ToArray());
		Add(DefaultConfig.Instance.GetLoggers().ToArray());
		Add(DefaultConfig.Instance.GetColumnProviders().ToArray());

		Add(MarkdownExporter.GitHub);
	}
}
```

2. Have a csproj which targets desktop .NET and .NET Core:
`<TargetFrameworks>netcoreapp2.0;net46</TargetFrameworks>`

3. Compile your project with msbuild:
`sudo msbuild /p:Configuration=Release BenchmarkDotNet.sln`

4. Run the exe with mono:
`sudo mono samples/BenchmarkDotNet.Samples/bin/Release/net46/BenchmarkDotNet.Samples.exe`

![image](https://user-images.githubusercontent.com/6011991/36570585-013c187a-1833-11e8-89de-72af28c3c139.png)


**Important**: Mono Host can now build both Mono and .NET Core benchmarks. .NET Core Host can not build Mono benchmarks. (it would require some extra work and I simply don't have time for it now)

**Comment by TheAngryByrd** [comment]
🎸 thanks a bunch!

**Comment by AndreyAkinshin** [comment]
@adamsitnik,
> Important: Mono Host can now build both Mono and .NET Core benchmarks. .NET Core Host can not build Mono benchmarks. (it would require some extra work and I simply don't have time for it now)

Could you please add a few lines about it in the documentation?
