### ISSUE TITLE
Benchmarking support for AI Processors

### ISSUE THREAD

**Issue by hybridware** [dotnet/BenchmarkDotNet#819]
Please add Benchmarking support for AI Processors or Graphics Cards optimised for Machine Learning.
The application should have a dedicated Machine Learning Perf Benchmarking option

**Comment by adamsitnik** [comment]
Hi @hybridware 

BenchmarkDotNet runs the code that you provide, which can be Machine Learning using graphics card or anything else. 

An example is [ML.NET](https://github.com/dotnet/machinelearning/tree/master/test/Microsoft.ML.Benchmarks) which uses BDN for benchmarking, but internally does most of the computations in native code.  BDN does not control where the code is going to be executed, it just runs the code as it is.

We are not going to add any special case for AI or something else because it's possible to benchmark it today.
