### ISSUE TITLE
Strange max frequency values on Windows

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#859]
In v0.11.0, we introduced advanced `CpuInfo` which contains the maximum CPU frequency.
On Windows, this value is based on the `wmic` output (`CurrentClockSpeed`). It turned out that sometimes these values look pretty strange: the evaluated frequency can be lower than the brand string frequency. Sometimes the difference between brand string and evaluated frequencies is about 0.01GHz.
The examples are listed below.

---

https://github.com/in-async/WeightedSamplingWithoutReplacement/blob/511652d58450e308be11378fe95cef55c984d2b6/README.md
```
Intel Core i5-3570K CPU 3.40GHz (Max: 3.30GHz) (Ivy Bridge), 1 CPU, 4 logical and 4 physical cores
```

---

https://github.com/silver-xu/Span-Memory-Benchmark/blob/d574522be1077e0c058afc9c711bc7970da7bb6f/SpanMemoryBenchmark/bin/Release/netcoreapp2.1/BenchmarkDotNet.Artifacts/results/SpanSample.Benchmarks-report-github.md
```
Intel Core i7-6650U CPU 2.20GHz (Max: 2.21GHz) (Skylake), 1 CPU, 4 logical and 2 physical cores
```

---

https://github.com/evilguest/linq2d/blob/9eaac5164bc9ffd4b160aaab93b9cde77b0b871c/README.md
```
Intel Core i7-6600U CPU 2.60GHz (Max: 2.61GHz) (Skylake), 1 CPU, 4 logical and 2 physical cores
```

---

https://github.com/ryzngard/Chipotle.CSV/blob/71d39352b02aea990834c2e2ae541ff6c5f45bfb/BenchmarkDotNet.Artifacts/Combined.md
```
Intel Core i7-8650U CPU 1.90GHz (Max: 1.91GHz) (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
```

---

https://github.com/JohanLarsson/BenchmarkBox/blob/d90f963540248f7b4071ea01bc52597d7743f815/BenchmarkBox/FindVsFirstOrDefault.md
```
Intel Xeon CPU E5-2637 v4 3.50GHz (Max: 3.49GHz), 2 CPU, 16 logical and 8 physical cores
```

---

https://github.com/dhhoang/IonDotnet/blob/87053280a9328d901cae2ca7f3aa4eb5f49aed37/README.md
```
Intel Core i7-6700HQ CPU 2.60GHz (Max: 2.59GHz) (Skylake), 1 CPU, 8 logical and 4 physical cores
```

---

**Comment by AndreyAkinshin** [comment]
@Rizzen could you take a look?

**Comment by AndreyAkinshin** [comment]
A relevant question on serverfault.com: https://serverfault.com/questions/121669/difference-between-currentclockspeed-and-maxclockspeed

**Comment by Rizzen** [comment]
So, I have repro using my laptop and eco-mode. I also made workaround and experiments using both `MaxClockSpeed` and `CurrentClockSpeed` - and `MaxClockSpeed` always returns same result while `CurrentClockSpeed` values was different. I hope that using `MaxClockSpeed` instead of `CurrentClockSpeed` will help to fix that issue.
 I'll provide PR with fix soon and it would be nice if someone check it on his own laptop.

**Comment by filzrev** [comment]
It's not a major issue, though.
I've observed similar behaviors on GitHub Actions CI in a Windows environment.

**1. Sometimes `MaxFrequency` is lower than `NominalFrequency`**
I've observed following value shown when running on Windows
> 2.80GHz (Max: 2.79GHz)
```
Intel Xeon Platinum 8370C CPU 2.80GHz (Max: 2.79GHz), 1 CPU, 4 logical and 2 physical cores
Memory: 15.99 GB Total, 12.46 GB Available
  [Host] : .NET Framework 4.8.1 (4.8.9325.0), X64 RyuJIT VectorSize=256
```

It's caused because Windows WIM/CIM returns `MaxFrequencyHz: 2793` instead of `2800`.

```
Name : Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
NumberOfCores : 2
NumberOfLogicalProcessors : 4
MaxClockSpeed : 2793
```

**2. Lower CPU frequency is reported on `AMD EPYC 7763`**
This CPU frequency is announced as `2.45GHz`.
But BenchmarkDotNet show CPU frequency as `2.44Ghz`

```
AMD EPYC 7763 2.44GHz, 1 CPU, 4 logical and 2 physical cores
Memory: 15.99 GB Total, 12.28 GB Available
.NET SDK 10.0.201
  [Host] : .NET 8.0.26 (8.0.26, 8.0.2626.16921), X64 RyuJIT x86-64-v3
```

This behavior is caused, because followin CIM query returns `2455` instead of `2450`.

> Get-CimInstance Win32_Processor -Property MaxClockSpeed

In addition to this, `systeminfo` command also returns 2445Mhz as CPU frequency.
```
Processor(s):                  1 Processor(s) Installed.
                               [01]: AMD64 Family 25 Model 1 Stepping 1 AuthenticAMD ~2445 Mhz
```
