### ISSUE TITLE
Missing images in docs

### ISSUE THREAD

**Issue by Maximusya** [dotnet/BenchmarkDotNet#998]
https://benchmarkdotnet.org/ contains broken links to images published from https://github.com/dotnet/BenchmarkDotNet/tree/master/docs/images

Example:
https://benchmarkdotnet.org/: ```<img src="images/rplot.png" alt="">``` from ```![](images/rplot.png)```

https://benchmarkdotnet.org/images/rplot.png is 404.

But docs for specific version (even for the latest one - but explicitly selected) contain img src that work:
https://benchmarkdotnet.org/v0.11.3/images/rplot.png is 200.

Docs built locally (according to https://benchmarkdotnet.org/articles/contributing/documentation.html) produce a site with working img src both for implicit latest and for explicit versions. But as I mentioned in #831 - I am missing the difference between the docs generation/deployment process for local and production environments.

**Comment by AndreyAkinshin** [comment]
@Maximusya thanks for the report. The problem was about casing: we had the `Images` folder instead of the `images` folder in the repository.

P.S. You can find the full actual sources of the currently deployed documentation in the `gh-pages` branch:  https://github.com/dotnet/BenchmarkDotNet/tree/gh-pages
